# Generated by Django 5.2.12 on 2026-04-12 13:05

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
        ('netbox_rpki', '0007_intentderivationrun_routingintentprofile_and_more'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedRoaAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('authorization_key', models.CharField(max_length=64)),
                ('prefix_cidr_text', models.CharField(max_length=64)),
                ('address_family', models.CharField(max_length=8)),
                ('origin_asn_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('external_object_id', models.CharField(blank=True, max_length=200)),
                ('is_stale', models.BooleanField(default=False)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-fetched_at', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ROAChangePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ROAChangePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=16)),
                ('before_state_json', models.JSONField(blank=True, default=dict)),
                ('after_state_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='publishedroaresult',
            name='netbox_rpki_publishedroaresult_run_roa_unique',
        ),
        migrations.RemoveConstraint(
            model_name='roaintentmatch',
            name='netbox_rpki_roaintentmatch_roa_intent_roa_unique',
        ),
        migrations.AlterField(
            model_name='publishedroaresult',
            name='roa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_reconciliation_results', to='netbox_rpki.roa'),
        ),
        migrations.AlterField(
            model_name='roaintentmatch',
            name='roa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intent_matches', to='netbox_rpki.roa'),
        ),
        migrations.AddField(
            model_name='importedroaauthorization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_roa_authorizations', to='netbox_rpki.organization'),
        ),
        migrations.AddField(
            model_name='importedroaauthorization',
            name='origin_asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_roa_authorizations', to='ipam.asn'),
        ),
        migrations.AddField(
            model_name='importedroaauthorization',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_roa_authorizations', to='ipam.prefix'),
        ),
        migrations.AddField(
            model_name='importedroaauthorization',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='importedroaauthorization',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='publishedroaresult',
            name='imported_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_reconciliation_results', to='netbox_rpki.importedroaauthorization'),
        ),
        migrations.AddField(
            model_name='roaintentmatch',
            name='imported_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intent_matches', to='netbox_rpki.importedroaauthorization'),
        ),
        migrations.AddField(
            model_name='roaintentresult',
            name='best_imported_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_result_matches', to='netbox_rpki.importedroaauthorization'),
        ),
        migrations.AddConstraint(
            model_name='publishedroaresult',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', True), ('roa__isnull', False)), fields=('reconciliation_run', 'roa'), name='netbox_rpki_publishedroaresult_run_roa_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedroaresult',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', False), ('roa__isnull', True)), fields=('reconciliation_run', 'imported_authorization'), name='netbox_rpki_publishedresult_run_imported_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedroaresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('imported_authorization__isnull', True), ('roa__isnull', False)), models.Q(('imported_authorization__isnull', False), ('roa__isnull', True)), _connector='OR'), name='netbox_rpki_publishedroaresult_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='roaintentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', True), ('roa__isnull', False)), fields=('roa_intent', 'roa'), name='netbox_rpki_roaintentmatch_roa_intent_roa_unique'),
        ),
        migrations.AddConstraint(
            model_name='roaintentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', False), ('roa__isnull', True)), fields=('roa_intent', 'imported_authorization'), name='netbox_rpki_roaintentmatch_roa_intent_imported_unique'),
        ),
        migrations.AddConstraint(
            model_name='roaintentmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('imported_authorization__isnull', True), ('roa__isnull', False)), models.Q(('imported_authorization__isnull', False), ('roa__isnull', True)), _connector='OR'), name='netbox_rpki_roaintentmatch_exactly_one_source'),
        ),
        migrations.AddField(
            model_name='providersnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_snapshots', to='netbox_rpki.organization'),
        ),
        migrations.AddField(
            model_name='providersnapshot',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='providersnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='importedroaauthorization',
            name='provider_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_roa_authorizations', to='netbox_rpki.providersnapshot'),
        ),
        migrations.AddField(
            model_name='roareconciliationrun',
            name='provider_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='netbox_rpki.providersnapshot'),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roa_change_plans', to='netbox_rpki.organization'),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='source_reconciliation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_plans', to='netbox_rpki.roareconciliationrun'),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='change_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='netbox_rpki.roachangeplan'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='imported_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.importedroaauthorization'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='roa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.roa'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='roa_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.roaintent'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='importedroaauthorization',
            constraint=models.UniqueConstraint(fields=('provider_snapshot', 'authorization_key'), name='netbox_rpki_importedroaauth_snapshot_key_unique'),
        ),
    ]
