# Generated by Django 5.2.12 on 2026-04-12 13:53

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0008_importedroaauthorization_providersnapshot_and_more'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpkiProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(default='arin', max_length=32)),
                ('transport', models.CharField(default='production', max_length=16)),
                ('org_handle', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('api_base_url', models.CharField(default='https://reg.arin.net', max_length=255)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='pending', max_length=32)),
                ('last_sync_summary_json', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_accounts', to='netbox_rpki.organization')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_imported', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_sync_runs', to='netbox_rpki.organization')),
                ('provider_snapshot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_run', to='netbox_rpki.providersnapshot')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='netbox_rpki.rpkiprovideraccount')),
            ],
            options={
                'ordering': ('-started_at', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='providersnapshot',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='netbox_rpki.rpkiprovideraccount'),
        ),
        migrations.AddConstraint(
            model_name='rpkiprovideraccount',
            constraint=models.UniqueConstraint(fields=('organization', 'provider_type', 'org_handle'), name='netbox_rpki_provideraccount_org_provider_handle_unique'),
        ),
    ]
