# Generated by Django 5.2.12 on 2026-04-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rpki', '0009_rpkiprovideraccount_providersyncrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpkiprovideraccount',
            name='ca_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
