# Generated by Django 5.2.12 on 2026-04-12 16:49

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0010_rpkiprovideraccount_ca_handle'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roachangeplan',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='apply_requested_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='apply_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='approved_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roa_change_plans', to='netbox_rpki.rpkiprovideraccount'),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='provider_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roa_change_plans', to='netbox_rpki.providersnapshot'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='provider_operation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='provider_payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProviderWriteExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('execution_mode', models.CharField(max_length=16)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_payload_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('change_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_write_executions', to='netbox_rpki.roachangeplan')),
                ('followup_provider_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followup_write_executions', to='netbox_rpki.providersnapshot')),
                ('followup_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_write_executions', to='netbox_rpki.providersyncrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_write_executions', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_executions', to='netbox_rpki.rpkiprovideraccount')),
                ('provider_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_executions', to='netbox_rpki.providersnapshot')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-started_at', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
