# Generated by Django 5.2.12 on 2026-04-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
        ('netbox_rpki', '0014_roachangeplan_governance_and_approvalrecord'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aspaprovider',
            constraint=models.UniqueConstraint(fields=('aspa', 'provider_as'), name='netbox_rpki_aspaprovider_aspa_provider_unique'),
        ),
    ]
