# Generated by Codex on 2026-04-12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
        ('netbox_rpki', '0016_alter_publishedroaresult_result_type_importedaspa_and_more'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASPAIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('intent_key', models.CharField(max_length=64)),
                ('explanation', models.TextField(blank=True)),
                ('customer_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspa_customer_intents', to='ipam.asn')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspa_intents', to='netbox_rpki.organization')),
                ('provider_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspa_provider_intents', to='ipam.asn')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ASPAIntentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('match_kind', models.CharField(choices=[('exact', 'Exact'), ('customer_mismatch', 'Customer Mismatch'), ('provider_mismatch', 'Provider Mismatch'), ('stale_candidate', 'Stale Candidate')], default='exact', max_length=32)),
                ('is_best_match', models.BooleanField(default=False)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intent_matches', to='netbox_rpki.aspa')),
                ('aspa_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_matches', to='netbox_rpki.aspaintent')),
                ('imported_aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intent_matches', to='netbox_rpki.importedaspa')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ASPAReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('comparison_scope', models.CharField(choices=[('local_roa_records', 'Local ROA Records'), ('local_aspa_records', 'Local ASPA Records'), ('provider_imported', 'Provider Imported'), ('mixed', 'Mixed')], default='local_aspa_records', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('intent_count', models.PositiveIntegerField(default=0)),
                ('published_aspa_count', models.PositiveIntegerField(default=0)),
                ('result_summary_json', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspa_reconciliation_runs', to='netbox_rpki.organization')),
                ('provider_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aspa_reconciliation_runs', to='netbox_rpki.providersnapshot')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-started_at', 'name'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ASPAIntentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('result_type', models.CharField(choices=[('match', 'Match'), ('missing', 'Missing'), ('missing_provider', 'Missing Provider'), ('customer_mismatch', 'Customer Mismatch'), ('provider_mismatch', 'Provider Mismatch'), ('stale', 'Stale'), ('unscoped', 'Unscoped')], default='match', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=16)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('aspa_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_results', to='netbox_rpki.aspaintent')),
                ('best_aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_result_matches', to='netbox_rpki.aspa')),
                ('best_imported_aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_result_matches', to='netbox_rpki.importedaspa')),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_results', to='netbox_rpki.aspareconciliationrun')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublishedASPAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('result_type', models.CharField(choices=[('matched', 'Matched'), ('orphaned', 'Orphaned'), ('duplicate', 'Duplicate'), ('extra_provider', 'Extra Provider'), ('missing_provider', 'Missing Provider'), ('customer_mismatch', 'Customer Mismatch'), ('stale', 'Stale'), ('unscoped', 'Unscoped')], default='matched', max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=16)),
                ('matched_intent_count', models.PositiveIntegerField(default=0)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_reconciliation_results', to='netbox_rpki.aspa')),
                ('imported_aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_reconciliation_results', to='netbox_rpki.importedaspa')),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_aspa_results', to='netbox_rpki.aspareconciliationrun')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='aspaintent',
            constraint=models.UniqueConstraint(fields=('organization', 'intent_key'), name='netbox_rpki_aspaintent_org_intent_key_unique'),
        ),
        migrations.AddIndex(
            model_name='aspaintent',
            index=models.Index(fields=['organization', 'customer_as', 'provider_as'], name='nb_rpki_ai_org_pair_idx'),
        ),
        migrations.AddConstraint(
            model_name='aspaintentmatch',
            constraint=models.UniqueConstraint(fields=('aspa_intent', 'aspa'), condition=models.Q(aspa__isnull=False, imported_aspa__isnull=True), name='netbox_rpki_aspaintentmatch_aspa_intent_aspa_unique'),
        ),
        migrations.AddConstraint(
            model_name='aspaintentmatch',
            constraint=models.UniqueConstraint(fields=('aspa_intent', 'imported_aspa'), condition=models.Q(aspa__isnull=True, imported_aspa__isnull=False), name='netbox_rpki_aspaintentmatch_aspa_intent_imported_unique'),
        ),
        migrations.AddConstraint(
            model_name='aspaintentmatch',
            constraint=models.CheckConstraint(condition=models.Q(aspa__isnull=False, imported_aspa__isnull=True) | models.Q(aspa__isnull=True, imported_aspa__isnull=False), name='netbox_rpki_aspaintentmatch_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='aspaintentresult',
            constraint=models.UniqueConstraint(fields=('reconciliation_run', 'aspa_intent'), name='netbox_rpki_aspaintentresult_run_intent_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedasparesult',
            constraint=models.UniqueConstraint(fields=('reconciliation_run', 'aspa'), condition=models.Q(aspa__isnull=False, imported_aspa__isnull=True), name='netbox_rpki_publishedasparesult_run_aspa_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedasparesult',
            constraint=models.UniqueConstraint(fields=('reconciliation_run', 'imported_aspa'), condition=models.Q(aspa__isnull=True, imported_aspa__isnull=False), name='netbox_rpki_publishedasparesult_run_imported_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedasparesult',
            constraint=models.CheckConstraint(condition=models.Q(aspa__isnull=False, imported_aspa__isnull=True) | models.Q(aspa__isnull=True, imported_aspa__isnull=False), name='netbox_rpki_publishedasparesult_exactly_one_source'),
        ),
    ]
