# Generated by Copilot on 2026-04-12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0018_roa_analysis_contract'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSnapshotDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('compared_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diffs_as_base', to='netbox_rpki.providersnapshot')),
                ('comparison_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diffs_as_comparison', to='netbox_rpki.providersnapshot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_snapshot_diffs', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_diffs', to='netbox_rpki.rpkiprovideraccount')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-compared_at', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderSnapshotDiffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('object_family', models.CharField(choices=[('roa_authorizations', 'ROA Authorizations'), ('aspas', 'ASPAs'), ('ca_metadata', 'CA Metadata'), ('parent_links', 'Parent Links'), ('child_links', 'Child Links'), ('resource_entitlements', 'Resource Entitlements'), ('publication_points', 'Publication Points'), ('certificate_inventory', 'Certificate Inventory'), ('signed_object_inventory', 'Signed Object Inventory')], default='roa_authorizations', max_length=64)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('changed', 'Changed'), ('unchanged', 'Unchanged'), ('reappeared', 'Reappeared'), ('stale', 'Stale')], default='changed', max_length=32)),
                ('provider_identity', models.CharField(blank=True, max_length=512)),
                ('external_object_id', models.CharField(blank=True, max_length=200)),
                ('before_state_json', models.JSONField(blank=True, default=dict)),
                ('after_state_json', models.JSONField(blank=True, default=dict)),
                ('prefix_cidr_text', models.CharField(blank=True, max_length=64)),
                ('origin_asn_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('customer_as_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_as_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('related_handle', models.CharField(blank=True, max_length=200)),
                ('certificate_identifier', models.CharField(blank=True, max_length=200)),
                ('publication_uri', models.CharField(blank=True, max_length=500)),
                ('signed_object_uri', models.CharField(blank=True, max_length=500)),
                ('is_stale', models.BooleanField(default=False)),
                ('external_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_diff_items', to='netbox_rpki.externalobjectreference')),
                ('snapshot_diff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='netbox_rpki.providersnapshotdiff')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('object_family', 'change_type', 'provider_identity', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='providersnapshotdiff',
            constraint=models.UniqueConstraint(fields=('base_snapshot', 'comparison_snapshot'), name='netbox_rpki_providersnapshotdiff_snapshot_pair_unique'),
        ),
    ]