# Generated by Copilot on 2026-04-12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rpki', '0020_imported_krill_tier1_families'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedSignedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('signed_object_key', models.CharField(max_length=64)),
                ('signed_object_type', models.CharField(choices=[('roa', 'ROA'), ('manifest', 'Manifest'), ('aspa', 'ASPA'), ('rsc', 'RSC'), ('tak', 'Trust Anchor Key'), ('ghostbusters', 'Ghostbusters'), ('other', 'Other')], default='other', max_length=32)),
                ('publication_uri', models.CharField(blank=True, max_length=500)),
                ('signed_object_uri', models.CharField(blank=True, max_length=500)),
                ('object_hash', models.CharField(blank=True, max_length=64)),
                ('body_base64', models.TextField(blank=True)),
                ('external_object_id', models.CharField(blank=True, max_length=200)),
                ('is_stale', models.BooleanField(default=False)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('external_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_signed_objects', to='netbox_rpki.externalobjectreference')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_signed_objects', to='netbox_rpki.organization')),
                ('provider_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_signed_objects', to='netbox_rpki.providersnapshot')),
                ('publication_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_signed_objects', to='netbox_rpki.importedpublicationpoint')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='importedsignedobject',
            constraint=models.UniqueConstraint(fields=('provider_snapshot', 'signed_object_key'), name='nb_rpki_impsignedobj_snap_key_uniq'),
        ),
    ]
