# Generated by Django 5.2.12 on 2026-04-13 23:11

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0028_imported_publication_authored_links'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASPAChangePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=16)),
                ('plan_semantic', models.CharField(blank=True, max_length=24, null=True)),
                ('provider_operation', models.CharField(blank=True, max_length=32)),
                ('provider_payload_json', models.JSONField(blank=True, default=dict)),
                ('before_state_json', models.JSONField(blank=True, default=dict)),
                ('after_state_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='change_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to='netbox_rpki.roachangeplan'),
        ),
        migrations.AlterField(
            model_name='providerwriteexecution',
            name='change_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_write_executions', to='netbox_rpki.roachangeplan'),
        ),
        migrations.CreateModel(
            name='ASPAChangePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('ticket_reference', models.CharField(blank=True, max_length=200)),
                ('change_reference', models.CharField(blank=True, max_length=200)),
                ('maintenance_window_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_window_end', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('apply_started_at', models.DateTimeField(blank=True, null=True)),
                ('apply_requested_by', models.CharField(blank=True, max_length=150)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspa_change_plans', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aspa_change_plans', to='netbox_rpki.rpkiprovideraccount')),
                ('provider_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aspa_change_plans', to='netbox_rpki.providersnapshot')),
                ('source_reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_plans', to='netbox_rpki.aspareconciliationrun')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='aspa_change_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to='netbox_rpki.aspachangeplan'),
        ),
        migrations.AddField(
            model_name='providerwriteexecution',
            name='aspa_change_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_write_executions', to='netbox_rpki.aspachangeplan'),
        ),
        migrations.AddConstraint(
            model_name='approvalrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aspa_change_plan__isnull', True), ('change_plan__isnull', False)), models.Q(('aspa_change_plan__isnull', False), ('change_plan__isnull', True)), _connector='OR'), name='netbox_rpki_approvalrecord_exactly_one_plan_target'),
        ),
        migrations.AddConstraint(
            model_name='providerwriteexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aspa_change_plan__isnull', True), ('change_plan__isnull', False)), models.Q(('aspa_change_plan__isnull', False), ('change_plan__isnull', True)), _connector='OR'), name='netbox_rpki_providerwriteexecution_exactly_one_plan_target'),
        ),
        migrations.AddField(
            model_name='aspachangeplanitem',
            name='aspa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.aspa'),
        ),
        migrations.AddField(
            model_name='aspachangeplanitem',
            name='aspa_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.aspaintent'),
        ),
        migrations.AddField(
            model_name='aspachangeplanitem',
            name='change_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='netbox_rpki.aspachangeplan'),
        ),
        migrations.AddField(
            model_name='aspachangeplanitem',
            name='imported_aspa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.importedaspa'),
        ),
        migrations.AddField(
            model_name='aspachangeplanitem',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='aspachangeplanitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='aspachangeplan',
            index=models.Index(fields=['organization', 'status'], name='nb_rpki_acp_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aspachangeplan',
            index=models.Index(fields=['provider_account', 'status'], name='nb_rpki_acp_prv_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='aspachangeplan',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_window_start__isnull', True), ('maintenance_window_end__isnull', True), ('maintenance_window_end__gte', models.F('maintenance_window_start')), _connector='OR'), name='netbox_rpki_aspachangeplan_valid_maintenance_window'),
        ),
        migrations.AddIndex(
            model_name='aspachangeplanitem',
            index=models.Index(fields=['change_plan', 'action_type'], name='nb_rpki_acpi_plan_action_idx'),
        ),
        migrations.AddIndex(
            model_name='aspachangeplanitem',
            index=models.Index(fields=['change_plan', 'plan_semantic'], name='nb_rpki_acpi_plan_sem_idx'),
        ),
    ]
