# Generated by Django 5.2.12 on 2026-04-14 00:57

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0029_aspachangeplanitem_alter_approvalrecord_change_plan_and_more'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROALintAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_reference', models.CharField(blank=True, max_length=200)),
                ('change_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('change_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lint_acknowledgements', to='netbox_rpki.roachangeplan')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='netbox_rpki.roalintfinding')),
                ('lint_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='netbox_rpki.roalintrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roa_lint_acknowledgements', to='netbox_rpki.organization')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-acknowledged_at', '-created', 'name'),
                'constraints': [models.UniqueConstraint(fields=('change_plan', 'finding'), name='netbox_rpki_roalintack_change_plan_finding_unique')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ROALintSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('finding_code', models.CharField(max_length=64)),
                ('scope_type', models.CharField(default='intent', max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('lifted_by', models.CharField(blank=True, max_length=150)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True)),
                ('intent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lint_suppressions', to='netbox_rpki.routingintentprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roa_lint_suppressions', to='netbox_rpki.organization')),
                ('roa_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lint_suppressions', to='netbox_rpki.roaintent')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-created', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('intent_profile__isnull', True), ('roa_intent__isnull', False), ('scope_type', 'intent')), models.Q(('intent_profile__isnull', False), ('roa_intent__isnull', True), ('scope_type', 'profile')), _connector='OR'), name='netbox_rpki_roalintsuppression_exact_scope_target'), models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True), ('scope_type', 'intent')), fields=('finding_code', 'roa_intent'), name='netbox_rpki_roalintsuppression_active_intent_unique'), models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True), ('scope_type', 'profile')), fields=('finding_code', 'intent_profile'), name='netbox_rpki_roalintsuppression_active_profile_unique')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
