# Generated by Django 5.2.12 on 2026-04-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0030_roalintacknowledgement_roalintsuppression'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roalintsuppression',
            name='netbox_rpki_roalintsuppression_active_intent_unique',
        ),
        migrations.RemoveConstraint(
            model_name='roalintsuppression',
            name='netbox_rpki_roalintsuppression_active_profile_unique',
        ),
        migrations.AddField(
            model_name='roalintsuppression',
            name='fact_context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='roalintsuppression',
            name='fact_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='roalintsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True), ('scope_type', 'intent')), fields=('finding_code', 'roa_intent', 'fact_fingerprint'), name='netbox_rpki_roalintsuppression_active_intent_unique'),
        ),
        migrations.AddConstraint(
            model_name='roalintsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True), ('scope_type', 'profile')), fields=('finding_code', 'intent_profile', 'fact_fingerprint'), name='netbox_rpki_roalintsuppression_active_profile_unique'),
        ),
    ]
