# Generated by Django 5.2.12 on 2026-04-14 06:04

from django.db import migrations, models


def backfill_simulation_contract_fields(apps, schema_editor):
    ROAValidationSimulationRun = apps.get_model('netbox_rpki', 'ROAValidationSimulationRun')
    ROAValidationSimulationResult = apps.get_model('netbox_rpki', 'ROAValidationSimulationResult')

    for run in ROAValidationSimulationRun.objects.all().iterator():
        summary_json = run.summary_json or {}
        run.plan_fingerprint = summary_json.get('plan_fingerprint', '')
        run.overall_approval_posture = summary_json.get('overall_approval_posture', 'informational')
        run.is_current_for_plan = bool(summary_json.get('is_current_for_plan', False))
        run.partially_constrained = bool(summary_json.get('partially_constrained', False))
        run.save(update_fields=(
            'plan_fingerprint',
            'overall_approval_posture',
            'is_current_for_plan',
            'partially_constrained',
        ))

    for result in ROAValidationSimulationResult.objects.all().iterator():
        details_json = result.details_json or {}
        result.approval_impact = details_json.get('approval_impact', 'informational')
        result.scenario_type = details_json.get('scenario_type', '')
        result.save(update_fields=('approval_impact', 'scenario_type'))


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0032_bulkintentrun_routingintenttemplate_and_more'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roavalidationsimulationresult',
            name='approval_impact',
            field=models.CharField(
                choices=[
                    ('informational', 'Informational'),
                    ('acknowledgement_required', 'Acknowledgement Required'),
                    ('blocking', 'Blocking'),
                ],
                default='informational',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='roavalidationsimulationresult',
            name='scenario_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='roavalidationsimulationrun',
            name='is_current_for_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roavalidationsimulationrun',
            name='overall_approval_posture',
            field=models.CharField(
                choices=[
                    ('informational', 'Informational'),
                    ('acknowledgement_required', 'Acknowledgement Required'),
                    ('blocking', 'Blocking'),
                ],
                default='informational',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='roavalidationsimulationrun',
            name='partially_constrained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roavalidationsimulationrun',
            name='plan_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(
            backfill_simulation_contract_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='roavalidationsimulationresult',
            index=models.Index(fields=['simulation_run', 'approval_impact'], name='nb_rpki_simres_run_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='roavalidationsimulationresult',
            index=models.Index(fields=['simulation_run', 'scenario_type'], name='nb_rpki_simres_run_scen_idx'),
        ),
        migrations.AddIndex(
            model_name='roavalidationsimulationrun',
            index=models.Index(fields=['change_plan', 'overall_approval_posture'], name='nb_rpki_simrun_plan_post_idx'),
        ),
        migrations.AddIndex(
            model_name='roavalidationsimulationrun',
            index=models.Index(fields=['change_plan', 'is_current_for_plan'], name='nb_rpki_simrun_plan_curr_idx'),
        ),
    ]
