# Generated by Django 5.2.12 on 2026-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rpki', '0033_roavalidationsimulationresult_approval_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='simulation_review_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
