# Generated by Django 5.2.12 on 2026-04-14 16:30

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0034_approvalrecord_simulation_review_json'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROALintRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('finding_code', models.CharField(help_text='The lint rule code from LINT_RULE_SPECS this override applies to.', max_length=64)),
                ('severity_override', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], help_text='Leave blank to use the rule default.', max_length=16)),
                ('approval_impact_override', models.CharField(blank=True, help_text='One of: informational, acknowledgement_required, blocking. Leave blank to use the rule default.', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roa_lint_rule_configs', to='netbox_rpki.organization')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [
                    models.UniqueConstraint(fields=('organization', 'finding_code'), name='netbox_rpki_roalintruleconfig_org_code_unique'),
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
