# Generated by Django 5.2.12 on 2026-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0035_add_roa_lint_rule_config'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roalintsuppression',
            name='netbox_rpki_roalintsuppression_exact_scope_target',
        ),
        migrations.AddField(
            model_name='roalintsuppression',
            name='prefix_cidr_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='roalintsuppression',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('intent_profile__isnull', True), ('prefix_cidr_text', ''), ('roa_intent__isnull', False), ('scope_type', 'intent')), models.Q(('intent_profile__isnull', False), ('prefix_cidr_text', ''), ('roa_intent__isnull', True), ('scope_type', 'profile')), models.Q(('intent_profile__isnull', True), ('prefix_cidr_text', ''), ('roa_intent__isnull', True), ('scope_type', 'org')), models.Q(('intent_profile__isnull', True), ('prefix_cidr_text__gt', ''), ('roa_intent__isnull', True), ('scope_type', 'prefix')), _connector='OR'), name='netbox_rpki_roalintsuppression_exact_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='roalintsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True), ('scope_type', 'org')), fields=('finding_code', 'organization'), name='netbox_rpki_roalintsuppression_active_org_unique'),
        ),
        migrations.AddConstraint(
            model_name='roalintsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('lifted_at__isnull', True), ('scope_type', 'prefix')), fields=('finding_code', 'organization', 'prefix_cidr_text'), name='netbox_rpki_roalintsuppression_active_prefix_unique'),
        ),
    ]
