# Generated by Django 5.2.12 on 2026-04-14 14:30

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0036_add_lint_suppression_org_prefix_scopes'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASPAChangePlanRollbackBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('rollback_delta_json', models.JSONField(default=dict)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('approved', 'Approved'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed')], default='available', max_length=16)),
                ('ticket_reference', models.CharField(blank=True, max_length=200)),
                ('change_reference', models.CharField(blank=True, max_length=200)),
                ('maintenance_window_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_window_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('apply_requested_by', models.CharField(blank=True, max_length=150)),
                ('apply_started_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('apply_response_json', models.JSONField(blank=True, default=dict)),
                ('apply_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspa_rollback_bundles', to='netbox_rpki.organization')),
                ('source_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_bundle', to='netbox_rpki.aspachangeplan')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ROAChangePlanRollbackBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('rollback_delta_json', models.JSONField(default=dict, help_text='The inverse of the applied delta. ROA creates become withdraws; withdraws become creates.')),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('approved', 'Approved'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed')], default='available', max_length=16)),
                ('ticket_reference', models.CharField(blank=True, max_length=200)),
                ('change_reference', models.CharField(blank=True, max_length=200)),
                ('maintenance_window_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_window_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('apply_requested_by', models.CharField(blank=True, max_length=150)),
                ('apply_started_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('apply_response_json', models.JSONField(blank=True, default=dict)),
                ('apply_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roa_rollback_bundles', to='netbox_rpki.organization')),
                ('source_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_bundle', to='netbox_rpki.roachangeplan')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='aspachangeplanrollbackbundle',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_window_start__isnull', True), ('maintenance_window_end__isnull', True), ('maintenance_window_end__gte', models.F('maintenance_window_start')), _connector='OR'), name='netbox_rpki_aspa_rollback_valid_mw'),
        ),
        migrations.AddConstraint(
            model_name='roachangeplanrollbackbundle',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_window_start__isnull', True), ('maintenance_window_end__isnull', True), ('maintenance_window_end__gte', models.F('maintenance_window_start')), _connector='OR'), name='netbox_rpki_roa_rollback_valid_mw'),
        ),
    ]
