# Generated by Django 5.2.12 on 2026-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rpki', '0037_change_plan_rollback_bundles'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspachangeplan',
            name='requires_secondary_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspachangeplan',
            name='secondary_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspachangeplan',
            name='secondary_approved_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='requires_secondary_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='secondary_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roachangeplan',
            name='secondary_approved_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
