# Generated by Django 5.2.12 on 2026-04-14 16:45

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0038_change_plan_dual_approval_fields'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleHealthPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(editable=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_stale_after_minutes', models.PositiveIntegerField(default=120)),
                ('roa_expiry_warning_days', models.PositiveIntegerField(default=30)),
                ('certificate_expiry_warning_days', models.PositiveIntegerField(default=30)),
                ('exception_expiry_warning_days', models.PositiveIntegerField(default=30)),
                ('publication_exchange_failure_threshold', models.PositiveIntegerField(default=1)),
                ('publication_stale_after_minutes', models.PositiveIntegerField(default=180)),
                ('certificate_expired_grace_minutes', models.PositiveIntegerField(default=0)),
                ('alert_repeat_after_minutes', models.PositiveIntegerField(default=360)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_policies', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_policies', to='netbox_rpki.rpkiprovideraccount')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='lifecyclehealthpolicy',
            constraint=models.UniqueConstraint(
                condition=models.Q(('provider_account__isnull', True)),
                fields=('organization',),
                name='nb_rpki_lchpolicy_org_default_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='lifecyclehealthpolicy',
            constraint=models.UniqueConstraint(
                condition=models.Q(('provider_account__isnull', False)),
                fields=('provider_account',),
                name='nb_rpki_lchpolicy_provider_unique',
            ),
        ),
    ]