# Generated by Django 5.2.12 on 2026-04-14 17:10

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0039_add_lifecycle_health_policy'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleHealthHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(editable=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('target_url', models.CharField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('event_kinds_json', models.JSONField(blank=True, default=list)),
                ('send_resolved', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_hooks', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_hooks', to='netbox_rpki.rpkiprovideraccount')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hooks', to='netbox_rpki.lifecyclehealthpolicy')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LifecycleHealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(editable=True, max_length=200)),
                ('event_kind', models.CharField(choices=[('sync_stale', 'Sync Stale'), ('sync_failed', 'Sync Failed'), ('roa_expiring', 'ROA Expiring'), ('certificate_expiring', 'Certificate Expiring'), ('exception_expiring', 'Exception Expiring'), ('publication_stale', 'Publication Stale'), ('publication_exchange_failed', 'Publication Exchange Failed'), ('publication_attention', 'Publication Attention'), ('publication_diff', 'Publication Diff')], max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('repeated', 'Repeated'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_emitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('delivery_error', models.TextField(blank=True)),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='netbox_rpki.lifecyclehealthhook')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_events', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_events', to='netbox_rpki.rpkiprovideraccount')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='netbox_rpki.lifecyclehealthpolicy')),
                ('related_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_events', to='netbox_rpki.providersnapshot')),
                ('related_snapshot_diff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_health_events', to='netbox_rpki.providersnapshotdiff')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-last_seen_at', '-created'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='lifecyclehealthevent',
            constraint=models.UniqueConstraint(fields=('hook', 'dedupe_key'), name='nb_rpki_lchevent_hook_dedupe_unique'),
        ),
    ]
