# Generated by Django 5.2.12 on 2026-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rpki', '0040_add_lifecycle_health_hook_and_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lifecyclehealthevent',
            name='nb_rpki_lchevent_hook_dedupe_unique',
        ),
        migrations.AddConstraint(
            model_name='lifecyclehealthevent',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['open', 'repeated'])),
                fields=('hook', 'dedupe_key'),
                name='nb_rpki_lchevent_hook_dedupe_unique',
            ),
        ),
    ]
