# Generated by Django 5.2.12 on 2026-04-15 00:30

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0045_irr_coordination_run_and_result'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrChangePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=16)),
                ('write_support_mode', models.CharField(choices=[('unsupported', 'Unsupported'), ('preview_only', 'Preview Only'), ('apply_supported', 'Apply Supported')], default='unsupported', max_length=32)),
                ('ticket_reference', models.CharField(blank=True, max_length=200)),
                ('change_reference', models.CharField(blank=True, max_length=200)),
                ('maintenance_window_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_window_end', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('execution_requested_by', models.CharField(blank=True, max_length=150)),
                ('execution_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('coordination_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_plans', to='netbox_rpki.irrcoordinationrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irr_change_plans', to='netbox_rpki.organization')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plans', to='netbox_rpki.irrsnapshot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_plans', to='netbox_rpki.irrsource')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created', 'name'),
                'constraints': (
                    models.CheckConstraint(
                        condition=(
                            models.Q(maintenance_window_start__isnull=True)
                            | models.Q(maintenance_window_end__isnull=True)
                            | models.Q(maintenance_window_end__gte=models.F('maintenance_window_start'))
                        ),
                        name='nb_rpki_irrchangeplan_valid_maintenance_window',
                    ),
                ),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IrrChangePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('object_family', models.CharField(choices=[('route_object', 'Route Object'), ('route_set_membership', 'Route-Set Membership'), ('as_set_membership', 'AS-Set Membership'), ('aut_num_context', 'Aut-Num Context'), ('maintainer_supportability', 'Maintainer Supportability')], max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('modify', 'Modify'), ('replace', 'Replace'), ('delete', 'Delete'), ('noop', 'No-op')], default='noop', max_length=16)),
                ('stable_object_key', models.CharField(blank=True, max_length=255)),
                ('source_object_key', models.CharField(blank=True, max_length=255)),
                ('before_state_json', models.JSONField(blank=True, default=dict)),
                ('after_state_json', models.JSONField(blank=True, default=dict)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_summary_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('change_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='netbox_rpki.irrchangeplan')),
                ('coordination_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.irrcoordinationresult')),
                ('imported_aut_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.importedirrautnum')),
                ('imported_maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.importedirrmaintainer')),
                ('imported_route_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.importedirrrouteobject')),
                ('roa_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='irr_change_plan_items', to='netbox_rpki.roaintent')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
