# Generated by Django 5.2.12 on 2026-04-15 00:30

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0046_irr_change_plan_and_item'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrWriteExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('execution_mode', models.CharField(choices=[('preview', 'Preview'), ('apply', 'Apply')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=16)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_payload_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('change_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_executions', to='netbox_rpki.irrchangeplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irr_write_executions', to='netbox_rpki.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_executions', to='netbox_rpki.irrsource')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-started_at', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
