# Generated by Django 5.2.12 on 2026-04-15 07:46

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0049_telemetry_models'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingintentcontextgroup',
            name='inherits_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inheriting_groups', to='netbox_rpki.routingintentcontextgroup'),
        ),
        migrations.CreateModel(
            name='DelegatedAuthorizationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='customer', max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('asn', models.BigIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegated_authorization_entities', to='netbox_rpki.organization')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('organization', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ManagedAuthorizationRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(default='managing_party', max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('service_uri', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('delegated_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_authorization_relationships', to='netbox_rpki.delegatedauthorizationentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_authorization_relationships', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_authorization_relationships', to='netbox_rpki.rpkiprovideraccount')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('organization', 'delegated_entity', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DelegatedPublicationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('parent_ca_handle', models.CharField(blank=True, max_length=100)),
                ('child_ca_handle', models.CharField(blank=True, max_length=100)),
                ('publication_server_uri', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegated_publication_workflows', to='netbox_rpki.organization')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('managed_relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_workflows', to='netbox_rpki.managedauthorizationrelationship')),
            ],
            options={
                'ordering': ('organization', 'managed_relationship', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoutingIntentPolicyBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('context_groups', models.ManyToManyField(blank=True, related_name='policy_bundles', to='netbox_rpki.routingintentcontextgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_intent_policy_bundles', to='netbox_rpki.organization')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('organization', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuthoredCaRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('child_ca_handle', models.CharField(max_length=100)),
                ('parent_ca_handle', models.CharField(blank=True, max_length=100)),
                ('relationship_type', models.CharField(default='parent', max_length=16)),
                ('status', models.CharField(default='active', max_length=32)),
                ('service_uri', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('imported_child_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_ca_relationships', to='netbox_rpki.importedchildlink')),
                ('imported_parent_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_ca_relationships', to='netbox_rpki.importedparentlink')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_ca_relationships', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_ca_relationships', to='netbox_rpki.rpkiprovideraccount')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('organization', 'child_ca_handle', 'parent_ca_handle'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'child_ca_handle', 'parent_ca_handle'), name='nb_rpki_authoredcarelationship_org_child_parent_unique')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='delegatedauthorizationentity',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='nb_rpki_delegatedauthentity_org_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='managedauthorizationrelationship',
            constraint=models.UniqueConstraint(fields=('organization', 'delegated_entity'), name='nb_rpki_managedauthrelationship_org_entity_unique'),
        ),
        migrations.AddConstraint(
            model_name='delegatedpublicationworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'managed_relationship', 'name'), name='nb_rpki_delegatedpubworkflow_org_rel_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='routingintentpolicybundle',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='nb_rpki_routingintentpolicybundle_org_name_unique'),
        ),
    ]
