# Generated by Django 5.2.12 on 2026-04-15 13:01

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0053_change_plan_delegated_scope'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoredAsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('set_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('delegated_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_as_sets', to='netbox_rpki.delegatedauthorizationentity')),
                ('managed_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_as_sets', to='netbox_rpki.managedauthorizationrelationship')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_as_sets', to='netbox_rpki.organization')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_as_sets', to='netbox_rpki.rpkiprovideraccount')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('organization', 'set_name', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuthoredAsSetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('member_type', models.CharField(default='asn', max_length=16)),
                ('member_asn_value', models.BigIntegerField(blank=True, null=True)),
                ('nested_set_name', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('authored_as_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='netbox_rpki.authoredasset')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('authored_as_set', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='authoredasset',
            constraint=models.UniqueConstraint(fields=('organization', 'set_name'), name='nb_rpki_authoredasset_org_set_name_unique'),
        ),
    ]
