# Generated by Django 5.2.12 on 2026-04-15 14:25

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0054_authoredasset_authoredassetmember_and_more'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalManagementException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('scope_type', models.CharField(choices=[('roa_prefix', 'ROA Prefix'), ('roa_object', 'ROA Object'), ('roa_imported', 'Imported ROA Object'), ('aspa_customer', 'ASPA Customer'), ('aspa_object', 'ASPA Object'), ('aspa_imported', 'Imported ASPA Object')], default='roa_prefix', max_length=32)),
                ('prefix_cidr_text', models.CharField(blank=True, max_length=64)),
                ('origin_asn_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customer_asn_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_asn_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('owner', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('review_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='netbox_rpki.aspa')),
                ('customer_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_customer_exceptions', to='ipam.asn')),
                ('imported_aspa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='netbox_rpki.importedaspa')),
                ('imported_authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='netbox_rpki.importedroaauthorization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='netbox_rpki.organization')),
                ('origin_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='ipam.asn')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='ipam.prefix')),
                ('provider_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_provider_exceptions', to='ipam.asn')),
                ('roa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='netbox_rpki.roa')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('organization', 'scope_type', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
