# Generated by Django 5.2.12 on 2026-04-15 15:05

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


def backfill_roa_objects(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    TaggedItem = apps.get_model('extras', 'TaggedItem')
    Roa = apps.get_model('netbox_rpki', 'Roa')
    RoaObject = apps.get_model('netbox_rpki', 'RoaObject')
    RoaPrefix = apps.get_model('netbox_rpki', 'RoaPrefix')
    RoaObjectPrefix = apps.get_model('netbox_rpki', 'RoaObjectPrefix')

    def ensure_content_type(model_name):
        content_type, _ = ContentType.objects.get_or_create(
            app_label='netbox_rpki',
            model=model_name,
        )
        return content_type

    roa_content_type = ensure_content_type('roa')
    roa_object_content_type = ensure_content_type('roaobject')
    roa_prefix_content_type = ensure_content_type('roaprefix')
    roa_object_prefix_content_type = ensure_content_type('roaobjectprefix')

    for roa in Roa.objects.select_related('signed_by__rpki_org', 'signed_object').all():
        organization_id = None
        if roa.signed_by_id is not None:
            organization_id = getattr(roa.signed_by, 'rpki_org_id', None)

        validation_state = 'unknown'
        if roa.signed_object_id and getattr(roa.signed_object, 'validation_state', None):
            validation_state = roa.signed_object.validation_state

        roa_object = RoaObject.objects.create(
            id=roa.pk,
            created=roa.created,
            last_updated=roa.last_updated,
            custom_field_data=roa.custom_field_data,
            comments=roa.comments,
            tenant_id=roa.tenant_id,
            name=roa.name,
            organization_id=organization_id,
            signed_object_id=roa.signed_object_id,
            origin_as_id=roa.origin_as_id,
            valid_from=roa.valid_from,
            valid_to=roa.valid_to,
            validation_state=validation_state,
        )
        TaggedItem.objects.bulk_create([
            TaggedItem(
                tag_id=tagged_item.tag_id,
                object_id=roa_object.pk,
                content_type_id=roa_object_content_type.pk,
            )
            for tagged_item in TaggedItem.objects.filter(
                content_type_id=roa_content_type.pk,
                object_id=roa.pk,
            )
        ])

    for roa_prefix in RoaPrefix.objects.select_related('prefix').all():
        prefix_cidr_text = ''
        if roa_prefix.prefix_id is not None and roa_prefix.prefix is not None:
            prefix_cidr_text = str(roa_prefix.prefix.prefix)

        roa_object_prefix = RoaObjectPrefix.objects.create(
            id=roa_prefix.pk,
            created=roa_prefix.created,
            last_updated=roa_prefix.last_updated,
            custom_field_data=roa_prefix.custom_field_data,
            comments=roa_prefix.comments,
            tenant_id=roa_prefix.tenant_id,
            roa_object_id=roa_prefix.roa_name_id,
            prefix_id=roa_prefix.prefix_id,
            prefix_cidr_text=prefix_cidr_text,
            max_length=roa_prefix.max_length,
            is_current=True,
        )
        TaggedItem.objects.bulk_create([
            TaggedItem(
                tag_id=tagged_item.tag_id,
                object_id=roa_object_prefix.pk,
                content_type_id=roa_object_prefix_content_type.pk,
            )
            for tagged_item in TaggedItem.objects.filter(
                content_type_id=roa_prefix_content_type.pk,
                object_id=roa_prefix.pk,
            )
        ])


def backfill_downstream_fks(apps, schema_editor):
    downstream_mappings = (
        ('ValidatedRoaPayload', 'roa_id', 'roa_object_id'),
        ('ExternalManagementException', 'roa_id', 'roa_object_id'),
        ('ROAIntentMatch', 'roa_id', 'roa_object_id'),
        ('ROAIntentResult', 'best_roa_id', 'best_roa_object_id'),
        ('PublishedROAResult', 'roa_id', 'roa_object_id'),
        ('ROAChangePlanItem', 'roa_id', 'roa_object_id'),
    )

    for model_name, old_field, new_field in downstream_mappings:
        model = apps.get_model('netbox_rpki', model_name)
        for row in model.objects.filter(**{f'{old_field}__isnull': False}):
            setattr(row, new_field, getattr(row, old_field))
            row.save(update_fields=[new_field])


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_rpki', '0055_externalmanagementexception'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoaObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roa_objects', to='netbox_rpki.organization')),
                ('origin_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roa_objects', to='ipam.asn')),
                ('signed_object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roa_extension', to='netbox_rpki.signedobject')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('validation_state', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('unknown', 'Unknown'), ('warning', 'Warning'), ('processing', 'Processing'), ('failed', 'Failed'), ('partial', 'Partial')], default='unknown', max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoaObjectPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('max_length', models.PositiveSmallIntegerField()),
                ('prefix_cidr_text', models.CharField(blank=True, max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roa_object_prefixes', to='ipam.prefix')),
                ('roa_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefix_authorizations', to='netbox_rpki.roaobject')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('roa_object', 'prefix_cidr_text'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RunPython(backfill_roa_objects, migrations.RunPython.noop),
        migrations.AddField(
            model_name='validatedroapayload',
            name='roa_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_payloads', to='netbox_rpki.roaobject'),
        ),
        migrations.AddField(
            model_name='externalmanagementexception',
            name='roa_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_management_exceptions', to='netbox_rpki.roaobject'),
        ),
        migrations.AddField(
            model_name='roaintentmatch',
            name='roa_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intent_matches', to='netbox_rpki.roaobject'),
        ),
        migrations.AddField(
            model_name='roaintentresult',
            name='best_roa_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_result_matches', to='netbox_rpki.roaobject'),
        ),
        migrations.AddField(
            model_name='publishedroaresult',
            name='roa_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_reconciliation_results', to='netbox_rpki.roaobject'),
        ),
        migrations.AddField(
            model_name='roachangeplanitem',
            name='roa_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_plan_items', to='netbox_rpki.roaobject'),
        ),
        migrations.RunPython(backfill_downstream_fks, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='roaintentmatch',
            name='netbox_rpki_roaintentmatch_roa_intent_roa_unique',
        ),
        migrations.RemoveConstraint(
            model_name='roaintentmatch',
            name='netbox_rpki_roaintentmatch_exactly_one_source',
        ),
        migrations.RemoveConstraint(
            model_name='roaintentmatch',
            name='netbox_rpki_roaintentmatch_roa_intent_imported_unique',
        ),
        migrations.RemoveConstraint(
            model_name='publishedroaresult',
            name='netbox_rpki_publishedroaresult_run_roa_unique',
        ),
        migrations.RemoveConstraint(
            model_name='publishedroaresult',
            name='netbox_rpki_publishedroaresult_exactly_one_source',
        ),
        migrations.RemoveConstraint(
            model_name='publishedroaresult',
            name='netbox_rpki_publishedresult_run_imported_unique',
        ),
        migrations.RemoveField(
            model_name='validatedroapayload',
            name='roa',
        ),
        migrations.RemoveField(
            model_name='externalmanagementexception',
            name='roa',
        ),
        migrations.RemoveField(
            model_name='roaintentmatch',
            name='roa',
        ),
        migrations.RemoveField(
            model_name='roaintentresult',
            name='best_roa',
        ),
        migrations.RemoveField(
            model_name='publishedroaresult',
            name='roa',
        ),
        migrations.RemoveField(
            model_name='roachangeplanitem',
            name='roa',
        ),
        migrations.AddConstraint(
            model_name='roaintentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', True), ('roa_object__isnull', False)), fields=('roa_intent', 'roa_object'), name='netbox_rpki_roaintentmatch_intent_roa_object_unique'),
        ),
        migrations.AddConstraint(
            model_name='roaintentmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('imported_authorization__isnull', True), ('roa_object__isnull', False)), models.Q(('imported_authorization__isnull', False), ('roa_object__isnull', True)), _connector='OR'), name='netbox_rpki_roaintentmatch_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='roaintentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', False), ('roa_object__isnull', True)), fields=('roa_intent', 'imported_authorization'), name='netbox_rpki_roaintentmatch_roa_intent_imported_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedroaresult',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', True), ('roa_object__isnull', False)), fields=('reconciliation_run', 'roa_object'), name='netbox_rpki_publishedroaresult_run_roa_object_unique'),
        ),
        migrations.AddConstraint(
            model_name='publishedroaresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('imported_authorization__isnull', True), ('roa_object__isnull', False)), models.Q(('imported_authorization__isnull', False), ('roa_object__isnull', True)), _connector='OR'), name='netbox_rpki_publishedroaresult_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='publishedroaresult',
            constraint=models.UniqueConstraint(condition=models.Q(('imported_authorization__isnull', False), ('roa_object__isnull', True)), fields=('reconciliation_run', 'imported_authorization'), name='netbox_rpki_publishedresult_run_imported_unique'),
        ),
        migrations.DeleteModel(
            name='RoaPrefix',
        ),
        migrations.DeleteModel(
            name='Roa',
        ),
    ]
