from netbox_rpki import models

from .object_specs import (
    ApiSpec,
    FilterSetSpec,
    FilterFormSpec,
    FormSpec,
    GraphQLFilterFieldSpec,
    GraphQLFilterSpec,
    GraphQLSpec,
    GraphQLTypeSpec,
    LabelSpec,
    NavigationSpec,
    ObjectSpec,
    RouteSpec,
    TableSpec,
    ViewSpec,
)


def build_standard_object_spec(
    *,
    registry_key,
    model,
    class_prefix,
    route_slug=None,
    route_path_prefix=None,
    api_basename=None,
    graphql_detail_field_name=None,
    graphql_list_field_name=None,
    label_singular,
    label_plural,
    api_fields,
    brief_fields,
    filter_fields,
    search_fields,
    graphql_fields,
    navigation_group=None,
    navigation_label=None,
    navigation_order=None,
    api_read_only=False,
    ui_read_only=False,
    show_add_button=True,
):
    form_spec = None
    view_edit_class_name = None
    view_delete_class_name = None

    if not ui_read_only:
        form_spec = FormSpec(
            class_name=f"{class_prefix}Form",
            fields=api_fields + ("tenant", "comments", "tags"),
        )
        view_edit_class_name = f"{class_prefix}EditView"
        view_delete_class_name = f"{class_prefix}DeleteView"

    route_slug = route_slug or registry_key
    api_basename = api_basename or route_slug
    graphql_detail_field_name = graphql_detail_field_name or f"netbox_rpki_{route_slug}"
    graphql_list_field_name = graphql_list_field_name or f"netbox_rpki_{route_slug}_list"

    return ObjectSpec(
        registry_key=registry_key,
        model=model,
        labels=LabelSpec(singular=label_singular, plural=label_plural),
        routes=RouteSpec(slug=route_slug, path_prefix=route_path_prefix),
        api=ApiSpec(
            serializer_name=f"{class_prefix}Serializer",
            viewset_name=f"{class_prefix}ViewSet",
            basename=api_basename,
            fields=("id", "url",) + api_fields,
            brief_fields=brief_fields,
            read_only=api_read_only,
        ),
        filterset=FilterSetSpec(
            class_name=f"{class_prefix}FilterSet",
            fields=filter_fields,
            search_fields=search_fields,
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name=f"{class_prefix}Filter",
                fields=tuple(
                    GraphQLFilterFieldSpec(field_name=field_name, filter_kind=filter_kind)
                    for field_name, filter_kind in graphql_fields
                ),
            ),
            type=GraphQLTypeSpec(class_name=f"{class_prefix}Type"),
            detail_field_name=graphql_detail_field_name,
            list_field_name=graphql_list_field_name,
        ),
        form=form_spec,
        filter_form=FilterFormSpec(class_name=f"{class_prefix}FilterForm"),
        table=TableSpec(
            class_name=f"{class_prefix}Table",
            fields=("pk", "id",) + api_fields + ("comments", "tenant", "tags"),
            default_columns=brief_fields + ("comments", "tenant", "tags"),
            linkify_field="name",
        ),
        view=ViewSpec(
            list_class_name=f"{class_prefix}ListView",
            detail_class_name=f"{class_prefix}View",
            edit_class_name=view_edit_class_name,
            delete_class_name=view_delete_class_name,
            simple_detail=True,
        ),
        navigation=(
            NavigationSpec(
                group=navigation_group,
                label=navigation_label,
                order=navigation_order,
                show_add_button=show_add_button and not ui_read_only,
            )
            if navigation_group is not None
            else None
        ),
    )


OBJECT_SPECS = (
    ObjectSpec(
        registry_key="certificate",
        model=models.Certificate,
        labels=LabelSpec(singular="Certificate", plural="Certificates"),
        routes=RouteSpec(slug="certificate", path_prefix="certificate"),
        api=ApiSpec(
            serializer_name="CertificateSerializer",
            viewset_name="CertificateViewSet",
            basename="certificate",
            fields=(
                "id",
                "url",
                "name",
                "issuer",
                "subject",
                "serial",
                "valid_from",
                "valid_to",
                "auto_renews",
                "public_key",
                "private_key",
                "publication_url",
                "ca_repository",
                "self_hosted",
                "rpki_org",
            ),
            brief_fields=("name", "issuer", "subject", "serial", "rpki_org"),
        ),
        filterset=FilterSetSpec(
            class_name="CertificateFilterSet",
            fields=(
                "name",
                "issuer",
                "subject",
                "serial",
                "valid_from",
                "valid_to",
                "public_key",
                "private_key",
                "publication_url",
                "ca_repository",
                "rpki_org",
                "self_hosted",
                "tenant",
            ),
            search_fields=(
                "name__icontains",
                "issuer__icontains",
                "subject__icontains",
                "serial__icontains",
                "comments__icontains",
            ),
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name="CertificateFilter",
                fields=(
                    GraphQLFilterFieldSpec(field_name="name", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="issuer", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="subject", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="serial", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="auto_renews", filter_kind="bool"),
                    GraphQLFilterFieldSpec(field_name="self_hosted", filter_kind="bool"),
                    GraphQLFilterFieldSpec(field_name="rpki_org_id", filter_kind="id"),
                ),
            ),
            type=GraphQLTypeSpec(class_name="CertificateType"),
            detail_field_name="netbox_rpki_certificate",
            list_field_name="netbox_rpki_certificate_list",
        ),
        form=FormSpec(
            class_name="CertificateForm",
            fields=(
                "name",
                "issuer",
                "subject",
                "serial",
                "valid_from",
                "valid_to",
                "auto_renews",
                "public_key",
                "private_key",
                "publication_url",
                "ca_repository",
                "rpki_org",
                "self_hosted",
                "tenant",
                "comments",
                "tags",
            ),
        ),
        filter_form=FilterFormSpec(class_name="CertificateFilterForm"),
        table=TableSpec(
            class_name="CertificateTable",
            fields=(
                "pk",
                "id",
                "name",
                "issuer",
                "subject",
                "serial",
                "valid_from",
                "valid_to",
                "auto_renews",
                "public_key",
                "private_key",
                "publication_url",
                "ca_repository",
                "self_hosted",
                "rpki_org",
                "comments",
                "tenant",
                "tags",
            ),
            default_columns=(
                "name",
                "valid_from",
                "valid_to",
                "auto_renews",
                "self_hosted",
                "rpki_org",
                "comments",
                "tenant",
                "tags",
            ),
            linkify_field="name",
        ),
        view=ViewSpec(
            list_class_name="CertificateListView",
            detail_class_name="CertificateView",
            edit_class_name="CertificateEditView",
            delete_class_name="CertificateDeleteView",
        ),
        navigation=NavigationSpec(
            group="Resources",
            label="Resource Certificates",
            order=20,
        ),
    ),
    ObjectSpec(
        registry_key="organization",
        model=models.Organization,
        labels=LabelSpec(singular="Organization", plural="Organizations"),
        routes=RouteSpec(slug="organization", path_prefix="orgs"),
        api=ApiSpec(
            serializer_name="OrganizationSerializer",
            viewset_name="OrganizationViewSet",
            basename="organization",
            fields=("id", "url", "org_id", "name", "ext_url", "parent_rir"),
            brief_fields=("org_id", "name", "parent_rir"),
        ),
        filterset=FilterSetSpec(
            class_name="OrganizationFilterSet",
            fields=("org_id", "name", "parent_rir", "ext_url", "tenant"),
            search_fields=(
                "org_id__icontains",
                "name__icontains",
                "ext_url__icontains",
                "comments__icontains",
            ),
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name="OrganizationFilter",
                fields=(
                    GraphQLFilterFieldSpec(field_name="org_id", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="name", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="ext_url", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="parent_rir_id", filter_kind="id"),
                ),
            ),
            type=GraphQLTypeSpec(class_name="OrganizationType"),
            detail_field_name="netbox_rpki_organization",
            list_field_name="netbox_rpki_organization_list",
        ),
        form=FormSpec(
            class_name="OrganizationForm",
            fields=("org_id", "name", "parent_rir", "ext_url", "tenant", "comments", "tags"),
        ),
        filter_form=FilterFormSpec(class_name="OrganizationFilterForm"),
        table=TableSpec(
            class_name="OrganizationTable",
            fields=("pk", "id", "org_id", "name", "parent_rir", "ext_url", "comments", "tenant", "tags"),
            default_columns=("org_id", "name", "parent_rir", "ext_url", "comments", "tenant", "tags"),
            linkify_field="name",
        ),
        view=ViewSpec(
            list_class_name="OrganizationListView",
            detail_class_name="OrganizationView",
            edit_class_name="OrganizationEditView",
            delete_class_name="OrganizationDeleteView",
        ),
        navigation=NavigationSpec(
            group="Resources",
            label="RIR Customer Orgs",
            order=10,
        ),
    ),
    ObjectSpec(
        registry_key="roa",
        model=models.Roa,
        labels=LabelSpec(singular="ROA", plural="ROAs"),
        routes=RouteSpec(slug="roa", path_prefix="roa"),
        api=ApiSpec(
            serializer_name="RoaSerializer",
            viewset_name="RoaViewSet",
            basename="roa",
            fields=(
                "id",
                "url",
                "name",
                "origin_as",
                "valid_from",
                "valid_to",
                "auto_renews",
                "signed_by",
            ),
            brief_fields=("name", "origin_as"),
        ),
        filterset=FilterSetSpec(
            class_name="RoaFilterSet",
            fields=("name", "origin_as", "valid_from", "valid_to", "signed_by", "tenant"),
            search_fields=("name__icontains", "comments__icontains"),
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name="RoaFilter",
                fields=(
                    GraphQLFilterFieldSpec(field_name="name", filter_kind="str"),
                    GraphQLFilterFieldSpec(field_name="auto_renews", filter_kind="bool"),
                    GraphQLFilterFieldSpec(field_name="origin_as_id", filter_kind="id"),
                    GraphQLFilterFieldSpec(field_name="signed_by_id", filter_kind="id"),
                ),
            ),
            type=GraphQLTypeSpec(class_name="RoaType"),
            detail_field_name="netbox_rpki_roa",
            list_field_name="netbox_rpki_roa_list",
        ),
        form=FormSpec(
            class_name="RoaForm",
            fields=("name", "origin_as", "valid_from", "valid_to", "auto_renews", "signed_by", "tenant", "comments", "tags"),
        ),
        filter_form=FilterFormSpec(class_name="RoaFilterForm"),
        table=TableSpec(
            class_name="RoaTable",
            fields=("pk", "id", "name", "origin_as", "valid_from", "valid_to", "auto_renews", "signed_by", "comments", "tenant", "tags"),
            default_columns=("name", "origin_as", "valid_from", "valid_to", "auto_renews", "comments", "tenant", "tags"),
            linkify_field="name",
        ),
        view=ViewSpec(
            list_class_name="RoaListView",
            detail_class_name="RoaView",
            edit_class_name="RoaEditView",
            delete_class_name="RoaDeleteView",
        ),
        navigation=NavigationSpec(
            group="ROAs",
            label="ROAs",
            order=10,
        ),
    ),
    ObjectSpec(
        registry_key="roaprefix",
        model=models.RoaPrefix,
        labels=LabelSpec(singular="ROA Prefix", plural="ROA Prefixes"),
        routes=RouteSpec(slug="roaprefix", path_prefix="roaprefixes"),
        api=ApiSpec(
            serializer_name="RoaPrefixSerializer",
            viewset_name="RoaPrefixViewSet",
            basename="roaprefix",
            fields=("id", "url", "prefix", "max_length", "roa_name"),
            brief_fields=("id", "prefix", "max_length", "roa_name"),
        ),
        filterset=FilterSetSpec(
            class_name="RoaPrefixFilterSet",
            fields=("prefix", "max_length", "roa_name", "tenant"),
            search_fields=("prefix__prefix__icontains", "comments__icontains"),
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name="RoaPrefixFilter",
                fields=(
                    GraphQLFilterFieldSpec(field_name="prefix_id", filter_kind="id"),
                    GraphQLFilterFieldSpec(field_name="roa_name_id", filter_kind="id"),
                ),
            ),
            type=GraphQLTypeSpec(class_name="RoaPrefixType"),
            detail_field_name="netbox_rpki_roa_prefix",
            list_field_name="netbox_rpki_roa_prefix_list",
        ),
        form=FormSpec(
            class_name="RoaPrefixForm",
            fields=("prefix", "max_length", "roa_name", "tenant", "comments", "tags"),
        ),
        filter_form=FilterFormSpec(class_name="RoaPrefixFilterForm"),
        table=TableSpec(
            class_name="RoaPrefixTable",
            fields=("pk", "id", "prefix", "max_length", "roa_name", "comments", "tenant", "tags"),
            default_columns=("prefix", "max_length", "roa_name", "comments", "tenant", "tags"),
            linkify_field="pk",
        ),
        view=ViewSpec(
            list_class_name="RoaPrefixListView",
            detail_class_name="RoaPrefixView",
            edit_class_name="RoaPrefixEditView",
            delete_class_name="RoaPrefixDeleteView",
            simple_detail=True,
        ),
    ),
    ObjectSpec(
        registry_key="certificateprefix",
        model=models.CertificatePrefix,
        labels=LabelSpec(singular="Certificate Prefix", plural="Certificate Prefixes"),
        routes=RouteSpec(slug="certificateprefix", path_prefix="certificateprefixes"),
        api=ApiSpec(
            serializer_name="CertificatePrefixSerializer",
            viewset_name="CertificatePrefixViewSet",
            basename="certificateprefix",
            fields=("id", "url", "prefix", "certificate_name"),
            brief_fields=("id", "prefix", "certificate_name"),
        ),
        filterset=FilterSetSpec(
            class_name="CertificatePrefixFilterSet",
            fields=("prefix", "certificate_name", "tenant"),
            search_fields=("prefix__prefix__icontains", "comments__icontains"),
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name="CertificatePrefixFilter",
                fields=(
                    GraphQLFilterFieldSpec(field_name="prefix_id", filter_kind="id"),
                    GraphQLFilterFieldSpec(field_name="certificate_name_id", filter_kind="id"),
                ),
            ),
            type=GraphQLTypeSpec(class_name="CertificatePrefixType"),
            detail_field_name="netbox_rpki_certificate_prefix",
            list_field_name="netbox_rpki_certificate_prefix_list",
        ),
        form=FormSpec(
            class_name="CertificatePrefixForm",
            fields=("prefix", "certificate_name", "tenant", "comments", "tags"),
        ),
        filter_form=FilterFormSpec(class_name="CertificatePrefixFilterForm"),
        table=TableSpec(
            class_name="CertificatePrefixTable",
            fields=("pk", "id", "prefix", "certificate_name", "comments", "tenant", "tags"),
            default_columns=("prefix", "comments", "tenant", "tags"),
            linkify_field="pk",
        ),
        view=ViewSpec(
            list_class_name="CertificatePrefixListView",
            detail_class_name="CertificatePrefixView",
            edit_class_name="CertificatePrefixEditView",
            delete_class_name="CertificatePrefixDeleteView",
            simple_detail=True,
        ),
    ),
    ObjectSpec(
        registry_key="certificateasn",
        model=models.CertificateAsn,
        labels=LabelSpec(singular="Certificate ASN", plural="Certificate ASNs"),
        routes=RouteSpec(slug="certificateasn", path_prefix="certificateasns"),
        api=ApiSpec(
            serializer_name="CertificateAsnSerializer",
            viewset_name="CertificateAsnViewSet",
            basename="certificateasn",
            fields=("id", "url", "asn", "certificate_name2"),
            brief_fields=("id", "asn", "certificate_name2"),
        ),
        filterset=FilterSetSpec(
            class_name="CertificateAsnFilterSet",
            fields=("asn", "certificate_name2", "tenant"),
            search_fields=("certificate_name2__name__icontains", "comments__icontains"),
        ),
        graphql=GraphQLSpec(
            filter=GraphQLFilterSpec(
                class_name="CertificateAsnFilter",
                fields=(
                    GraphQLFilterFieldSpec(field_name="asn_id", filter_kind="id"),
                    GraphQLFilterFieldSpec(field_name="certificate_name2_id", filter_kind="id"),
                ),
            ),
            type=GraphQLTypeSpec(class_name="CertificateAsnType"),
            detail_field_name="netbox_rpki_certificate_asn",
            list_field_name="netbox_rpki_certificate_asn_list",
        ),
        form=FormSpec(
            class_name="CertificateAsnForm",
            fields=("asn", "certificate_name2", "tenant", "comments", "tags"),
        ),
        filter_form=FilterFormSpec(class_name="CertificateAsnFilterForm"),
        table=TableSpec(
            class_name="CertificateAsnTable",
            fields=("pk", "id", "asn", "certificate_name2", "comments", "tenant", "tags"),
            default_columns=("asn", "comments", "tenant", "tags"),
            linkify_field="pk",
        ),
        view=ViewSpec(
            list_class_name="CertificateAsnListView",
            detail_class_name="CertificateAsnView",
            edit_class_name="CertificateAsnEditView",
            delete_class_name="CertificateAsnDeleteView",
            simple_detail=True,
        ),
    ),
    build_standard_object_spec(
        registry_key="repository",
        model=models.Repository,
        class_prefix="Repository",
        label_singular="Repository",
        label_plural="Repositories",
        api_fields=(
            "name",
            "organization",
            "repository_type",
            "rsync_base_uri",
            "rrdp_notify_uri",
            "status",
            "last_observed_at",
        ),
        brief_fields=("name", "repository_type", "status"),
        filter_fields=("name", "organization", "repository_type", "status", "tenant"),
        search_fields=("name__icontains", "rsync_base_uri__icontains", "rrdp_notify_uri__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("repository_type", "str"),
            ("status", "str"),
        ),
        navigation_group="Resources",
        navigation_label="Repositories",
        navigation_order=30,
    ),
    build_standard_object_spec(
        registry_key="publicationpoint",
        model=models.PublicationPoint,
        class_prefix="PublicationPoint",
        label_singular="Publication Point",
        label_plural="Publication Points",
        api_fields=(
            "name",
            "organization",
            "repository",
            "publication_uri",
            "rsync_base_uri",
            "rrdp_notify_uri",
            "retrieval_state",
            "validation_state",
            "last_observed_at",
        ),
        brief_fields=("name", "repository", "validation_state"),
        filter_fields=("name", "organization", "repository", "retrieval_state", "validation_state", "tenant"),
        search_fields=("name__icontains", "publication_uri__icontains", "rrdp_notify_uri__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("repository_id", "id"),
            ("retrieval_state", "str"),
            ("validation_state", "str"),
        ),
        navigation_group="Resources",
        navigation_label="Publication Points",
        navigation_order=40,
    ),
    build_standard_object_spec(
        registry_key="trustanchor",
        model=models.TrustAnchor,
        class_prefix="TrustAnchor",
        label_singular="Trust Anchor",
        label_plural="Trust Anchors",
        api_fields=(
            "name",
            "organization",
            "subject",
            "subject_key_identifier",
            "rsync_uri",
            "rrdp_notify_uri",
            "status",
            "superseded_by",
        ),
        brief_fields=("name", "subject", "status"),
        filter_fields=("name", "organization", "status", "superseded_by", "tenant"),
        search_fields=("name__icontains", "subject__icontains", "subject_key_identifier__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("status", "str"),
            ("superseded_by_id", "id"),
        ),
        navigation_group="Trust",
        navigation_label="Trust Anchors",
        navigation_order=10,
    ),
    build_standard_object_spec(
        registry_key="trustanchorlocator",
        model=models.TrustAnchorLocator,
        class_prefix="TrustAnchorLocator",
        label_singular="Trust Anchor Locator",
        label_plural="Trust Anchor Locators",
        api_fields=("name", "trust_anchor", "rsync_uri", "https_uri", "public_key_info", "is_active"),
        brief_fields=("name", "trust_anchor", "is_active"),
        filter_fields=("name", "trust_anchor", "is_active", "tenant"),
        search_fields=("name__icontains", "rsync_uri__icontains", "https_uri__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("trust_anchor_id", "id"),
            ("is_active", "bool"),
        ),
        navigation_group="Trust",
        navigation_label="Trust Anchor Locators",
        navigation_order=20,
    ),
    build_standard_object_spec(
        registry_key="endentitycertificate",
        model=models.EndEntityCertificate,
        class_prefix="EndEntityCertificate",
        label_singular="End-Entity Certificate",
        label_plural="End-Entity Certificates",
        api_fields=(
            "name",
            "organization",
            "resource_certificate",
            "publication_point",
            "subject",
            "issuer",
            "serial",
            "ski",
            "aki",
            "valid_from",
            "valid_to",
            "public_key",
            "status",
        ),
        brief_fields=("name", "serial", "status"),
        filter_fields=("name", "organization", "resource_certificate", "publication_point", "serial", "status", "tenant"),
        search_fields=("name__icontains", "subject__icontains", "issuer__icontains", "serial__icontains", "ski__icontains", "aki__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("resource_certificate_id", "id"),
            ("publication_point_id", "id"),
            ("serial", "str"),
            ("status", "str"),
        ),
        navigation_group="Resources",
        navigation_label="EE Certificates",
        navigation_order=50,
    ),
    build_standard_object_spec(
        registry_key="signedobject",
        model=models.SignedObject,
        class_prefix="SignedObject",
        label_singular="Signed Object",
        label_plural="Signed Objects",
        api_fields=(
            "name",
            "organization",
            "object_type",
            "display_label",
            "resource_certificate",
            "ee_certificate",
            "publication_point",
            "current_manifest",
            "filename",
            "object_uri",
            "repository_uri",
            "content_hash",
            "serial_or_version",
            "cms_digest_algorithm",
            "cms_signature_algorithm",
            "publication_status",
            "validation_state",
            "valid_from",
            "valid_to",
            "raw_payload_reference",
        ),
        brief_fields=("name", "object_type", "publication_status", "validation_state"),
        filter_fields=(
            "name",
            "organization",
            "object_type",
            "resource_certificate",
            "ee_certificate",
            "publication_point",
            "current_manifest",
            "publication_status",
            "validation_state",
            "tenant",
        ),
        search_fields=(
            "name__icontains",
            "display_label__icontains",
            "filename__icontains",
            "object_uri__icontains",
            "repository_uri__icontains",
            "content_hash__icontains",
            "comments__icontains",
        ),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("object_type", "str"),
            ("resource_certificate_id", "id"),
            ("ee_certificate_id", "id"),
            ("publication_point_id", "id"),
            ("current_manifest_id", "id"),
            ("publication_status", "str"),
            ("validation_state", "str"),
        ),
        navigation_group="Objects",
        navigation_label="Signed Objects",
        navigation_order=10,
    ),
    build_standard_object_spec(
        registry_key="certificaterevocationlist",
        model=models.CertificateRevocationList,
        class_prefix="CertificateRevocationList",
        label_singular="Certificate Revocation List",
        label_plural="Certificate Revocation Lists",
        api_fields=(
            "name",
            "organization",
            "issuing_certificate",
            "publication_point",
            "manifest",
            "crl_number",
            "this_update",
            "next_update",
            "publication_uri",
            "retrieval_state",
            "validation_state",
        ),
        brief_fields=("name", "issuing_certificate", "crl_number"),
        filter_fields=(
            "name",
            "organization",
            "issuing_certificate",
            "publication_point",
            "manifest",
            "retrieval_state",
            "validation_state",
            "tenant",
        ),
        search_fields=("name__icontains", "crl_number__icontains", "publication_uri__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("issuing_certificate_id", "id"),
            ("publication_point_id", "id"),
            ("manifest_id", "id"),
            ("retrieval_state", "str"),
            ("validation_state", "str"),
        ),
        navigation_group="Resources",
        navigation_label="CRLs",
        navigation_order=60,
    ),
    build_standard_object_spec(
        registry_key="manifest",
        model=models.Manifest,
        class_prefix="Manifest",
        label_singular="Manifest",
        label_plural="Manifests",
        api_fields=("name", "signed_object", "manifest_number", "this_update", "next_update", "current_crl"),
        brief_fields=("name", "manifest_number", "current_crl"),
        filter_fields=("name", "signed_object", "current_crl", "tenant"),
        search_fields=("name__icontains", "manifest_number__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("signed_object_id", "id"),
            ("current_crl_id", "id"),
        ),
        navigation_group="Objects",
        navigation_label="Manifests",
        navigation_order=20,
    ),
    build_standard_object_spec(
        registry_key="trustanchorkey",
        model=models.TrustAnchorKey,
        class_prefix="TrustAnchorKey",
        label_singular="Trust Anchor Key",
        label_plural="Trust Anchor Keys",
        api_fields=(
            "name",
            "trust_anchor",
            "signed_object",
            "current_public_key",
            "next_public_key",
            "valid_from",
            "valid_to",
            "publication_uri",
            "supersedes",
        ),
        brief_fields=("name", "trust_anchor", "valid_to"),
        filter_fields=("name", "trust_anchor", "signed_object", "supersedes", "tenant"),
        search_fields=("name__icontains", "publication_uri__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("trust_anchor_id", "id"),
            ("signed_object_id", "id"),
            ("supersedes_id", "id"),
        ),
        navigation_group="Trust",
        navigation_label="Trust Anchor Keys",
        navigation_order=30,
    ),
    build_standard_object_spec(
        registry_key="aspa",
        model=models.ASPA,
        class_prefix="ASPA",
        label_singular="ASPA",
        label_plural="ASPAs",
        api_fields=("name", "organization", "signed_object", "customer_as", "valid_from", "valid_to", "validation_state"),
        brief_fields=("name", "customer_as", "validation_state"),
        filter_fields=("name", "organization", "signed_object", "customer_as", "validation_state", "tenant"),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("signed_object_id", "id"),
            ("customer_as_id", "id"),
            ("validation_state", "str"),
        ),
        navigation_group="Objects",
        navigation_label="ASPAs",
        navigation_order=30,
    ),
    build_standard_object_spec(
        registry_key="rsc",
        model=models.RSC,
        class_prefix="RSC",
        label_singular="RSC",
        label_plural="RSCs",
        api_fields=("name", "organization", "signed_object", "version", "digest_algorithm"),
        brief_fields=("name", "version", "digest_algorithm"),
        filter_fields=("name", "organization", "signed_object", "version", "digest_algorithm", "tenant"),
        search_fields=("name__icontains", "version__icontains", "digest_algorithm__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("signed_object_id", "id"),
            ("version", "str"),
            ("digest_algorithm", "str"),
        ),
        navigation_group="Objects",
        navigation_label="RSCs",
        navigation_order=40,
    ),
    build_standard_object_spec(
        registry_key="routercertificate",
        model=models.RouterCertificate,
        class_prefix="RouterCertificate",
        label_singular="Router Certificate",
        label_plural="Router Certificates",
        api_fields=(
            "name",
            "organization",
            "resource_certificate",
            "publication_point",
            "asn",
            "subject",
            "issuer",
            "serial",
            "ski",
            "router_public_key",
            "valid_from",
            "valid_to",
            "status",
        ),
        brief_fields=("name", "asn", "serial", "status"),
        filter_fields=("name", "organization", "resource_certificate", "publication_point", "asn", "serial", "status", "tenant"),
        search_fields=("name__icontains", "subject__icontains", "issuer__icontains", "serial__icontains", "ski__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("resource_certificate_id", "id"),
            ("publication_point_id", "id"),
            ("asn_id", "id"),
            ("serial", "str"),
            ("status", "str"),
        ),
        navigation_group="Resources",
        navigation_label="Router Certificates",
        navigation_order=70,
    ),
    build_standard_object_spec(
        registry_key="validatorinstance",
        model=models.ValidatorInstance,
        class_prefix="ValidatorInstance",
        label_singular="Validator Instance",
        label_plural="Validator Instances",
        api_fields=("name", "organization", "software_name", "software_version", "base_url", "status", "last_run_at"),
        brief_fields=("name", "software_name", "status"),
        filter_fields=("name", "organization", "software_name", "status", "tenant"),
        search_fields=("name__icontains", "software_name__icontains", "software_version__icontains", "base_url__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("software_name", "str"),
            ("status", "str"),
        ),
        navigation_group="Validation",
        navigation_label="Validator Instances",
        navigation_order=10,
    ),
    build_standard_object_spec(
        registry_key="validationrun",
        model=models.ValidationRun,
        class_prefix="ValidationRun",
        label_singular="Validation Run",
        label_plural="Validation Runs",
        api_fields=("name", "validator", "status", "started_at", "completed_at", "repository_serial"),
        brief_fields=("name", "validator", "status"),
        filter_fields=("name", "validator", "status", "tenant"),
        search_fields=("name__icontains", "repository_serial__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("validator_id", "id"),
            ("status", "str"),
        ),
        navigation_group="Validation",
        navigation_label="Validation Runs",
        navigation_order=20,
    ),
    build_standard_object_spec(
        registry_key="objectvalidationresult",
        model=models.ObjectValidationResult,
        class_prefix="ObjectValidationResult",
        label_singular="Object Validation Result",
        label_plural="Object Validation Results",
        api_fields=("name", "validation_run", "signed_object", "validation_state", "disposition", "observed_at", "reason"),
        brief_fields=("name", "validation_run", "validation_state"),
        filter_fields=("name", "validation_run", "signed_object", "validation_state", "disposition", "tenant"),
        search_fields=("name__icontains", "reason__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("validation_run_id", "id"),
            ("signed_object_id", "id"),
            ("validation_state", "str"),
            ("disposition", "str"),
        ),
        navigation_group="Validation",
        navigation_label="Object Validation Results",
        navigation_order=30,
    ),
    build_standard_object_spec(
        registry_key="validatedroapayload",
        model=models.ValidatedRoaPayload,
        class_prefix="ValidatedRoaPayload",
        label_singular="Validated ROA Payload",
        label_plural="Validated ROA Payloads",
        api_fields=("name", "validation_run", "roa", "prefix", "origin_as", "max_length"),
        brief_fields=("name", "prefix", "origin_as", "max_length"),
        filter_fields=("name", "validation_run", "roa", "prefix", "origin_as", "tenant"),
        search_fields=("name__icontains", "prefix__prefix__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("validation_run_id", "id"),
            ("roa_id", "id"),
            ("prefix_id", "id"),
            ("origin_as_id", "id"),
        ),
        navigation_group="Validation",
        navigation_label="Validated ROA Payloads",
        navigation_order=40,
    ),
    build_standard_object_spec(
        registry_key="validatedaspapayload",
        model=models.ValidatedAspaPayload,
        class_prefix="ValidatedAspaPayload",
        label_singular="Validated ASPA Payload",
        label_plural="Validated ASPA Payloads",
        api_fields=("name", "validation_run", "aspa", "customer_as", "provider_as"),
        brief_fields=("name", "customer_as", "provider_as"),
        filter_fields=("name", "validation_run", "aspa", "customer_as", "provider_as", "tenant"),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("validation_run_id", "id"),
            ("aspa_id", "id"),
            ("customer_as_id", "id"),
            ("provider_as_id", "id"),
        ),
        navigation_group="Validation",
        navigation_label="Validated ASPA Payloads",
        navigation_order=50,
    ),
    build_standard_object_spec(
        registry_key="routingintentprofile",
        model=models.RoutingIntentProfile,
        class_prefix="RoutingIntentProfile",
        label_singular="Routing Intent Profile",
        label_plural="Routing Intent Profiles",
        api_fields=(
            "name",
            "organization",
            "is_default",
            "status",
            "description",
            "selector_mode",
            "prefix_selector_query",
            "asn_selector_query",
            "default_max_length_policy",
            "allow_as0",
            "enabled",
        ),
        brief_fields=("name", "organization", "status", "enabled"),
        filter_fields=("name", "organization", "is_default", "status", "selector_mode", "enabled", "tenant"),
        search_fields=("name__icontains", "description__icontains", "prefix_selector_query__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("status", "str"),
            ("selector_mode", "str"),
            ("enabled", "bool"),
            ("is_default", "bool"),
        ),
        navigation_group="Intent",
        navigation_label="Routing Intent Profiles",
        navigation_order=10,
    ),
    build_standard_object_spec(
        registry_key="routingintentrule",
        model=models.RoutingIntentRule,
        class_prefix="RoutingIntentRule",
        label_singular="Routing Intent Rule",
        label_plural="Routing Intent Rules",
        api_fields=(
            "name",
            "intent_profile",
            "weight",
            "action",
            "address_family",
            "match_tenant",
            "match_vrf",
            "match_site",
            "match_region",
            "match_role",
            "match_tag",
            "match_custom_field",
            "origin_asn",
            "max_length_mode",
            "max_length_value",
            "enabled",
        ),
        brief_fields=("name", "intent_profile", "action", "enabled"),
        filter_fields=(
            "name",
            "intent_profile",
            "action",
            "address_family",
            "match_tenant",
            "match_vrf",
            "match_site",
            "match_region",
            "origin_asn",
            "enabled",
            "tenant",
        ),
        search_fields=("name__icontains", "match_role__icontains", "match_tag__icontains", "match_custom_field__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("intent_profile_id", "id"),
            ("action", "str"),
            ("address_family", "str"),
            ("origin_asn_id", "id"),
            ("enabled", "bool"),
        ),
        navigation_group="Intent",
        navigation_label="Routing Intent Rules",
        navigation_order=20,
    ),
    build_standard_object_spec(
        registry_key="roaintentoverride",
        model=models.ROAIntentOverride,
        class_prefix="ROAIntentOverride",
        label_singular="ROA Intent Override",
        label_plural="ROA Intent Overrides",
        api_fields=(
            "name",
            "organization",
            "intent_profile",
            "action",
            "prefix",
            "prefix_cidr_text",
            "origin_asn",
            "origin_asn_value",
            "max_length",
            "tenant_scope",
            "vrf_scope",
            "site_scope",
            "region_scope",
            "reason",
            "starts_at",
            "ends_at",
            "enabled",
        ),
        brief_fields=("name", "organization", "action", "enabled"),
        filter_fields=(
            "name",
            "organization",
            "intent_profile",
            "action",
            "prefix",
            "origin_asn",
            "tenant_scope",
            "vrf_scope",
            "site_scope",
            "region_scope",
            "enabled",
            "tenant",
        ),
        search_fields=("name__icontains", "prefix_cidr_text__icontains", "reason__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("intent_profile_id", "id"),
            ("action", "str"),
            ("prefix_id", "id"),
            ("origin_asn_id", "id"),
            ("enabled", "bool"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Intent Overrides",
        navigation_order=30,
    ),
    build_standard_object_spec(
        registry_key="intentderivationrun",
        model=models.IntentDerivationRun,
        class_prefix="IntentDerivationRun",
        label_singular="Intent Derivation Run",
        label_plural="Intent Derivation Runs",
        api_fields=(
            "name",
            "organization",
            "intent_profile",
            "status",
            "trigger_mode",
            "started_at",
            "completed_at",
            "input_fingerprint",
            "prefix_count_scanned",
            "intent_count_emitted",
            "warning_count",
            "error_summary",
        ),
        brief_fields=("name", "intent_profile", "status", "started_at"),
        filter_fields=("name", "organization", "intent_profile", "status", "trigger_mode", "tenant"),
        search_fields=("name__icontains", "input_fingerprint__icontains", "error_summary__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("intent_profile_id", "id"),
            ("status", "str"),
            ("trigger_mode", "str"),
        ),
        navigation_group="Intent",
        navigation_label="Intent Derivation Runs",
        navigation_order=40,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="roaintent",
        model=models.ROAIntent,
        class_prefix="ROAIntent",
        label_singular="ROA Intent",
        label_plural="ROA Intents",
        api_fields=(
            "name",
            "derivation_run",
            "organization",
            "intent_profile",
            "intent_key",
            "prefix",
            "prefix_cidr_text",
            "address_family",
            "origin_asn",
            "origin_asn_value",
            "is_as0",
            "max_length",
            "scope_tenant",
            "scope_vrf",
            "scope_site",
            "scope_region",
            "source_rule",
            "applied_override",
            "derived_state",
            "exposure_state",
            "explanation",
        ),
        brief_fields=("name", "intent_profile", "prefix", "origin_asn", "derived_state"),
        filter_fields=(
            "name",
            "derivation_run",
            "organization",
            "intent_profile",
            "prefix",
            "origin_asn",
            "address_family",
            "scope_tenant",
            "scope_vrf",
            "scope_site",
            "scope_region",
            "applied_override",
            "derived_state",
            "exposure_state",
            "tenant",
        ),
        search_fields=("name__icontains", "intent_key__icontains", "prefix_cidr_text__icontains", "explanation__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("derivation_run_id", "id"),
            ("organization_id", "id"),
            ("intent_profile_id", "id"),
            ("prefix_id", "id"),
            ("origin_asn_id", "id"),
            ("address_family", "str"),
            ("is_as0", "bool"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Intents",
        navigation_order=50,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="roaintentmatch",
        model=models.ROAIntentMatch,
        class_prefix="ROAIntentMatch",
        label_singular="ROA Intent Match",
        label_plural="ROA Intent Matches",
        api_fields=("name", "roa_intent", "roa", "imported_authorization", "match_kind", "is_best_match", "details_json"),
        brief_fields=("name", "roa_intent", "roa", "imported_authorization", "match_kind"),
        filter_fields=("name", "roa_intent", "roa", "imported_authorization", "match_kind", "is_best_match", "tenant"),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("roa_intent_id", "id"),
            ("roa_id", "id"),
            ("imported_authorization_id", "id"),
            ("match_kind", "str"),
            ("is_best_match", "bool"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Intent Matches",
        navigation_order=60,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="roareconciliationrun",
        model=models.ROAReconciliationRun,
        class_prefix="ROAReconciliationRun",
        label_singular="ROA Reconciliation Run",
        label_plural="ROA Reconciliation Runs",
        api_fields=(
            "name",
            "organization",
            "intent_profile",
            "basis_derivation_run",
            "provider_snapshot",
            "comparison_scope",
            "status",
            "started_at",
            "completed_at",
            "published_roa_count",
            "intent_count",
            "result_summary_json",
        ),
        brief_fields=("name", "intent_profile", "provider_snapshot", "comparison_scope", "status"),
        filter_fields=("name", "organization", "intent_profile", "basis_derivation_run", "provider_snapshot", "comparison_scope", "status", "tenant"),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("intent_profile_id", "id"),
            ("basis_derivation_run_id", "id"),
            ("provider_snapshot_id", "id"),
            ("comparison_scope", "str"),
            ("status", "str"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Reconciliation Runs",
        navigation_order=70,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="roaintentresult",
        model=models.ROAIntentResult,
        class_prefix="ROAIntentResult",
        label_singular="ROA Intent Result",
        label_plural="ROA Intent Results",
        api_fields=(
            "name",
            "reconciliation_run",
            "roa_intent",
            "result_type",
            "severity",
            "best_roa",
            "best_imported_authorization",
            "match_count",
            "details_json",
            "computed_at",
        ),
        brief_fields=("name", "roa_intent", "result_type", "severity", "best_roa", "best_imported_authorization"),
        filter_fields=("name", "reconciliation_run", "roa_intent", "result_type", "severity", "best_roa", "best_imported_authorization", "tenant"),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("reconciliation_run_id", "id"),
            ("roa_intent_id", "id"),
            ("result_type", "str"),
            ("severity", "str"),
            ("best_roa_id", "id"),
            ("best_imported_authorization_id", "id"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Intent Results",
        navigation_order=80,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="publishedroaresult",
        model=models.PublishedROAResult,
        class_prefix="PublishedROAResult",
        label_singular="Published ROA Result",
        label_plural="Published ROA Results",
        api_fields=(
            "name",
            "reconciliation_run",
            "roa",
            "imported_authorization",
            "result_type",
            "severity",
            "matched_intent_count",
            "details_json",
            "computed_at",
        ),
        brief_fields=("name", "roa", "imported_authorization", "result_type", "severity"),
        filter_fields=("name", "reconciliation_run", "roa", "imported_authorization", "result_type", "severity", "tenant"),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("reconciliation_run_id", "id"),
            ("roa_id", "id"),
            ("imported_authorization_id", "id"),
            ("result_type", "str"),
            ("severity", "str"),
        ),
        navigation_group="Intent",
        navigation_label="Published ROA Results",
        navigation_order=90,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="importedroaauthorization",
        model=models.ImportedRoaAuthorization,
        class_prefix="ImportedRoaAuthorization",
        label_singular="Imported ROA Authorization",
        label_plural="Imported ROA Authorizations",
        api_fields=(
            "name",
            "provider_snapshot",
            "organization",
            "authorization_key",
            "prefix",
            "prefix_cidr_text",
            "address_family",
            "origin_asn",
            "origin_asn_value",
            "max_length",
            "external_object_id",
            "external_reference",
            "is_stale",
            "payload_json",
        ),
        brief_fields=("name", "provider_snapshot", "prefix", "origin_asn", "origin_asn_value", "max_length"),
        filter_fields=("name", "provider_snapshot", "organization", "prefix", "address_family", "origin_asn", "is_stale", "tenant"),
        search_fields=("name__icontains", "prefix_cidr_text__icontains", "external_object_id__icontains", "comments__icontains"),
        graphql_fields=(("name", "str"), ("provider_snapshot_id", "id"), ("organization_id", "id"), ("prefix_id", "id"), ("origin_asn_id", "id"), ("origin_asn_value", "str"), ("max_length", "str"), ("is_stale", "bool")),
        navigation_group="Intent",
        navigation_label="Imported ROA Authorizations",
        navigation_order=110,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="roachangeplan",
        model=models.ROAChangePlan,
        class_prefix="ROAChangePlan",
        label_singular="ROA Change Plan",
        label_plural="ROA Change Plans",
        api_fields=(
            "name",
            "organization",
            "source_reconciliation_run",
            "provider_account",
            "provider_snapshot",
            "status",
            "ticket_reference",
            "change_reference",
            "maintenance_window_start",
            "maintenance_window_end",
            "approved_at",
            "approved_by",
            "apply_started_at",
            "apply_requested_by",
            "applied_at",
            "failed_at",
            "summary_json",
        ),
        brief_fields=("name", "organization", "source_reconciliation_run", "provider_account", "status"),
        filter_fields=(
            "name",
            "organization",
            "source_reconciliation_run",
            "provider_account",
            "provider_snapshot",
            "status",
            "tenant",
        ),
        search_fields=("name__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("source_reconciliation_run_id", "id"),
            ("provider_account_id", "id"),
            ("provider_snapshot_id", "id"),
            ("status", "str"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Change Plans",
        navigation_order=120,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="approvalrecord",
        model=models.ApprovalRecord,
        class_prefix="ApprovalRecord",
        label_singular="Approval Record",
        label_plural="Approval Records",
        api_fields=(
            "name",
            "organization",
            "change_plan",
            "disposition",
            "recorded_by",
            "recorded_at",
            "ticket_reference",
            "change_reference",
            "maintenance_window_start",
            "maintenance_window_end",
            "notes",
        ),
        brief_fields=(
            "name",
            "change_plan",
            "disposition",
            "recorded_by",
            "recorded_at",
            "ticket_reference",
            "change_reference",
        ),
        filter_fields=(
            "name",
            "organization",
            "change_plan",
            "disposition",
            "recorded_by",
            "recorded_at",
            "ticket_reference",
            "change_reference",
            "maintenance_window_start",
            "maintenance_window_end",
            "tenant",
        ),
        search_fields=(
            "name__icontains",
            "recorded_by__icontains",
            "ticket_reference__icontains",
            "change_reference__icontains",
            "notes__icontains",
            "comments__icontains",
        ),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("change_plan_id", "id"),
            ("disposition", "str"),
            ("recorded_by", "str"),
        ),
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="rpkiprovideraccount",
        model=models.RpkiProviderAccount,
        class_prefix="RpkiProviderAccount",
        route_slug="provideraccount",
        api_basename="provideraccount",
        graphql_detail_field_name="netbox_rpki_provideraccount",
        graphql_list_field_name="netbox_rpki_provideraccount_list",
        label_singular="Provider Account",
        label_plural="Provider Accounts",
        api_fields=(
            "name",
            "organization",
            "provider_type",
            "transport",
            "org_handle",
            "ca_handle",
            "api_key",
            "api_base_url",
            "sync_enabled",
            "sync_interval",
            "last_successful_sync",
            "last_sync_status",
            "last_sync_summary_json",
        ),
        brief_fields=("name", "organization", "provider_type", "org_handle", "ca_handle", "last_sync_status"),
        filter_fields=("name", "organization", "provider_type", "transport", "org_handle", "ca_handle", "sync_enabled", "sync_interval", "last_sync_status", "tenant"),
        search_fields=("name__icontains", "org_handle__icontains", "ca_handle__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("provider_type", "str"),
            ("transport", "str"),
            ("org_handle", "str"),
            ("ca_handle", "str"),
            ("sync_enabled", "bool"),
            ("last_sync_status", "str"),
        ),
        navigation_group="Intent",
        navigation_label="Provider Accounts",
        navigation_order=95,
    ),
    build_standard_object_spec(
        registry_key="providersnapshot",
        model=models.ProviderSnapshot,
        class_prefix="ProviderSnapshot",
        label_singular="Provider Snapshot",
        label_plural="Provider Snapshots",
        api_fields=("name", "provider_account", "organization", "provider_name", "status", "fetched_at", "completed_at", "summary_json"),
        brief_fields=("name", "provider_account", "organization", "provider_name", "status"),
        filter_fields=("name", "provider_account", "organization", "provider_name", "status", "tenant"),
        search_fields=("name__icontains", "provider_name__icontains", "comments__icontains"),
        graphql_fields=(("name", "str"), ("provider_account_id", "id"), ("organization_id", "id"), ("provider_name", "str"), ("status", "str")),
        navigation_group="Intent",
        navigation_label="Provider Snapshots",
        navigation_order=100,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="roachangeplanitem",
        model=models.ROAChangePlanItem,
        class_prefix="ROAChangePlanItem",
        label_singular="ROA Change Plan Item",
        label_plural="ROA Change Plan Items",
        api_fields=(
            "name",
            "change_plan",
            "action_type",
            "roa_intent",
            "roa",
            "imported_authorization",
            "provider_operation",
            "provider_payload_json",
            "before_state_json",
            "after_state_json",
            "reason",
        ),
        brief_fields=("name", "change_plan", "action_type", "roa_intent", "roa", "imported_authorization"),
        filter_fields=(
            "name",
            "change_plan",
            "action_type",
            "roa_intent",
            "roa",
            "imported_authorization",
            "provider_operation",
            "tenant",
        ),
        search_fields=("name__icontains", "reason__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("change_plan_id", "id"),
            ("action_type", "str"),
            ("roa_intent_id", "id"),
            ("roa_id", "id"),
            ("imported_authorization_id", "id"),
            ("provider_operation", "str"),
        ),
        navigation_group="Intent",
        navigation_label="ROA Change Plan Items",
        navigation_order=130,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="providerwriteexecution",
        model=models.ProviderWriteExecution,
        class_prefix="ProviderWriteExecution",
        label_singular="Provider Write Execution",
        label_plural="Provider Write Executions",
        api_fields=(
            "name",
            "organization",
            "provider_account",
            "provider_snapshot",
            "change_plan",
            "execution_mode",
            "status",
            "requested_by",
            "started_at",
            "completed_at",
            "item_count",
            "request_payload_json",
            "response_payload_json",
            "error",
            "followup_sync_run",
            "followup_provider_snapshot",
        ),
        brief_fields=("name", "provider_account", "change_plan", "execution_mode", "status", "started_at"),
        filter_fields=(
            "name",
            "organization",
            "provider_account",
            "provider_snapshot",
            "change_plan",
            "execution_mode",
            "status",
            "followup_sync_run",
            "followup_provider_snapshot",
            "tenant",
        ),
        search_fields=("name__icontains", "requested_by__icontains", "error__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("provider_account_id", "id"),
            ("provider_snapshot_id", "id"),
            ("change_plan_id", "id"),
            ("execution_mode", "str"),
            ("status", "str"),
        ),
        navigation_group="Intent",
        navigation_label="Provider Write Executions",
        navigation_order=107,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
    build_standard_object_spec(
        registry_key="providersyncrun",
        model=models.ProviderSyncRun,
        class_prefix="ProviderSyncRun",
        label_singular="Provider Sync Run",
        label_plural="Provider Sync Runs",
        api_fields=(
            "name",
            "organization",
            "provider_account",
            "provider_snapshot",
            "status",
            "started_at",
            "completed_at",
            "records_fetched",
            "records_imported",
            "error",
            "summary_json",
        ),
        brief_fields=("name", "provider_account", "provider_snapshot", "status", "started_at"),
        filter_fields=("name", "organization", "provider_account", "provider_snapshot", "status", "tenant"),
        search_fields=("name__icontains", "error__icontains", "comments__icontains"),
        graphql_fields=(
            ("name", "str"),
            ("organization_id", "id"),
            ("provider_account_id", "id"),
            ("provider_snapshot_id", "id"),
            ("status", "str"),
        ),
        navigation_group="Intent",
        navigation_label="Provider Sync Runs",
        navigation_order=105,
        api_read_only=True,
        ui_read_only=True,
        show_add_button=False,
    ),
)

API_OBJECT_SPECS = OBJECT_SPECS
GRAPHQL_OBJECT_SPECS = tuple(spec for spec in OBJECT_SPECS if spec.graphql is not None)
FILTERSET_OBJECT_SPECS = tuple(spec for spec in OBJECT_SPECS if spec.filterset is not None)
FORM_OBJECT_SPECS = tuple(spec for spec in OBJECT_SPECS if spec.form is not None)
FILTER_FORM_OBJECT_SPECS = tuple(spec for spec in OBJECT_SPECS if spec.filter_form is not None)
TABLE_OBJECT_SPECS = tuple(spec for spec in OBJECT_SPECS if spec.table is not None)
VIEW_OBJECT_SPECS = tuple(spec for spec in OBJECT_SPECS if spec.view is not None)
SIMPLE_DETAIL_VIEW_OBJECT_SPECS = tuple(spec for spec in VIEW_OBJECT_SPECS if spec.view.simple_detail)
OBJECT_SPEC_BY_REGISTRY_KEY = {spec.registry_key: spec for spec in OBJECT_SPECS}
MENU_GROUP_ORDER = ("Resources", "ROAs", "Objects", "Trust", "Intent", "Validation")


def get_object_spec(registry_key: str) -> ObjectSpec:
    return OBJECT_SPEC_BY_REGISTRY_KEY[registry_key]


def get_navigation_groups() -> tuple[tuple[str, tuple[ObjectSpec, ...]], ...]:
    groups = []
    for group_name in MENU_GROUP_ORDER:
        group_specs = tuple(
            sorted(
                (
                    spec
                    for spec in OBJECT_SPECS
                    if spec.has_menu_item and spec.navigation.group == group_name
                ),
                key=lambda spec: spec.navigation.order,
            )
        )
        if group_specs:
            groups.append((group_name, group_specs))

    return tuple(groups)
