#!/usr/bin/env bash
set -euo pipefail

DEVRUN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NETBOX_RELEASE="${NETBOX_RELEASE:-4.5.7}"
NETBOX_SRC="${NETBOX_SRC:-$HOME/src/netbox-v${NETBOX_RELEASE}}"
NETBOX_PROJECT_DIR="${NETBOX_PROJECT_DIR:-$NETBOX_SRC/netbox}"
VENV_DIR="${VENV_DIR:-$HOME/.virtualenvs/netbox-${NETBOX_RELEASE}}"
STATE_DIR="${STATE_DIR:-$HOME/.config/netbox-rpki-dev}"
CREDENTIALS_FILE="${CREDENTIALS_FILE:-$STATE_DIR/credentials.env}"
CONFIG_FILE="${CONFIG_FILE:-$NETBOX_PROJECT_DIR/netbox/configuration.py}"
ENV_FILE="${ENV_FILE:-$DEVRUN_DIR/.env}"
PLUGIN_NAME="netbox_rpki"
KRILL_ROOT="${KRILL_ROOT:-$HOME/src/krill_for_netbox_rpki}"
KRILL_START_SCRIPT="${KRILL_START_SCRIPT:-$KRILL_ROOT/scripts/start-krill.sh}"
KRILL_STOP_SCRIPT="${KRILL_STOP_SCRIPT:-$KRILL_ROOT/scripts/stop-krill.sh}"
KRILL_PID_FILE="${KRILL_PID_FILE:-$KRILL_ROOT/var/run/krill.pid}"
KRILL_CMD_PATTERN="${KRILL_CMD_PATTERN:-$KRILL_ROOT/cargo-root/bin/krill -c $KRILL_ROOT/etc/krill.conf}"
ROUTINATOR_RTR_PORT="${ROUTINATOR_RTR_PORT:-3323}"
ROUTINATOR_HTTP_PORT="${ROUTINATOR_HTTP_PORT:-8323}"
ROUTINATOR_METRICS_PORT="${ROUTINATOR_METRICS_PORT:-9556}"
ROUTINATOR_BASE_URL="${ROUTINATOR_BASE_URL:-http://127.0.0.1:${ROUTINATOR_HTTP_PORT}}"
ROUTINATOR_STATUS_URL="${ROUTINATOR_STATUS_URL:-${ROUTINATOR_BASE_URL}/api/v1/status}"

find_runserver_pids() {
    local pid
    local cwd

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        cwd="$(readlink -f "/proc/$pid/cwd" 2>/dev/null || true)"
        if [ "$cwd" = "$NETBOX_PROJECT_DIR" ]; then
            printf '%s\n' "$pid"
        fi
    done < <(pgrep -u "$USER" -f 'manage.py runserver' || true)
}

find_worker_pids() {
    local pid
    local cwd

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        cwd="$(readlink -f "/proc/$pid/cwd" 2>/dev/null || true)"
        if [ "$cwd" = "$NETBOX_PROJECT_DIR" ]; then
            printf '%s\n' "$pid"
        fi
    done < <(pgrep -u "$USER" -f 'manage.py rqworker default' || true)
}

find_krill_pids() {
    local pid

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        printf '%s\n' "$pid"
    done < <(pgrep -u "$USER" -f "$KRILL_CMD_PATTERN" || true)
}

runserver_is_running() {
    local pid

    while IFS= read -r pid; do
        if [ -n "$pid" ]; then
            return 0
        fi
    done < <(find_runserver_pids)

    return 1
}

krill_is_installed() {
    [ -x "$KRILL_START_SCRIPT" ] && [ -x "$KRILL_STOP_SCRIPT" ]
}

worker_is_running() {
    local pid

    while IFS= read -r pid; do
        if [ -n "$pid" ]; then
            return 0
        fi
    done < <(find_worker_pids)

    return 1
}

krill_is_running() {
    local pid

    while IFS= read -r pid; do
        if [ -n "$pid" ]; then
            return 0
        fi
    done < <(find_krill_pids)

    return 1
}

stop_runserver() {
    local pid
    local stopped=1

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        kill "$pid" >/dev/null 2>&1 || true
        stopped=0
    done < <(find_runserver_pids)

    return "$stopped"
}

start_krill() {
    if ! krill_is_installed; then
        return 1
    fi
    "$KRILL_START_SCRIPT"
}

stop_worker() {
    local pid
    local stopped=1

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        kill "$pid" >/dev/null 2>&1 || true
        stopped=0
    done < <(find_worker_pids)

    return "$stopped"
}

stop_krill() {
    if ! krill_is_installed; then
        return 1
    fi
    "$KRILL_STOP_SCRIPT"
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || {
        printf 'Missing required command: %s\n' "$1" >&2
        exit 1
    }
}

ensure_state_dir() {
    mkdir -p "$STATE_DIR"
    chmod 700 "$STATE_DIR"
}

load_credentials() {
    if [ -f "$CREDENTIALS_FILE" ]; then
        # The credentials file is generated by these scripts and uses shell-safe quoting.
        # Source it so escaped values round-trip correctly.
        set -a
        # shellcheck disable=SC1090
        . "$CREDENTIALS_FILE"
        set +a
    fi
}

docker_compose() {
    (
        cd "$DEVRUN_DIR"
        docker compose "$@"
    )
}

wait_for_postgres() {
    local attempt
    for attempt in $(seq 1 30); do
        if pg_isready -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
    done
    printf 'PostgreSQL did not become ready in time.\n' >&2
    return 1
}

wait_for_redis() {
    local attempt
    for attempt in $(seq 1 30); do
        if redis-cli -h 127.0.0.1 -p 6379 ping >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
    done
    printf 'Redis did not become ready in time.\n' >&2
    return 1
}

routinator_status_http_code() {
    curl -sS -o /dev/null -w '%{http_code}' --max-time 2 "$ROUTINATOR_STATUS_URL" || true
}

routinator_is_reachable() {
    case "$(routinator_status_http_code)" in
        200|301|302|303|307|308|503)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

routinator_is_ready() {
    [ "$(routinator_status_http_code)" = "200" ]
}

wait_for_routinator() {
    local attempt

    for attempt in $(seq 1 30); do
        if routinator_is_reachable; then
            return 0
        fi
        sleep 1
    done

    printf 'Routinator did not become reachable at %s in time.\n' "$ROUTINATOR_STATUS_URL" >&2
    return 1
}

extract_plugin_blocker() {
    python3 - "$1" <<'PY'
import pathlib
import re
import sys

text = pathlib.Path(sys.argv[1]).read_text(errors='replace')
patterns = [
    r'^ModuleNotFoundError: .+$',
    r'^ImportError: .+$',
    r'^ImproperlyConfigured: .+$',
    r'^RuntimeError: .+$',
    r'^Exception: .+$',
    r'^.+Error: .+$',
    r'^Unable to load plugin .+$',
]
for line in text.splitlines():
    stripped = line.strip()
    if not stripped or stripped.startswith('Traceback ') or stripped.startswith('File "'):
        continue
    if stripped.startswith('raise ') or stripped.startswith('During handling'):
        continue
    for pattern in patterns:
        if re.match(pattern, stripped):
            print(stripped)
            raise SystemExit(0)
for line in text.splitlines():
    stripped = line.strip()
    if stripped:
        print(stripped)
        break
PY
}
