#!/usr/bin/env bash
set -euo pipefail

DEVRUN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NETBOX_RELEASE="${NETBOX_RELEASE:-4.5.7}"
NETBOX_SRC="${NETBOX_SRC:-$HOME/src/netbox-v${NETBOX_RELEASE}}"
NETBOX_PROJECT_DIR="${NETBOX_PROJECT_DIR:-$NETBOX_SRC/netbox}"
VENV_DIR="${VENV_DIR:-$HOME/.virtualenvs/netbox-${NETBOX_RELEASE}}"
STATE_DIR="${STATE_DIR:-$HOME/.config/netbox-rpki-dev}"
CREDENTIALS_FILE="${CREDENTIALS_FILE:-$STATE_DIR/credentials.env}"
CONFIG_FILE="${CONFIG_FILE:-$NETBOX_PROJECT_DIR/netbox/configuration.py}"
ENV_FILE="${ENV_FILE:-$DEVRUN_DIR/.env}"
PLUGIN_NAME="netbox_rpki"

find_runserver_pids() {
    local pid
    local cwd

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        cwd="$(readlink -f "/proc/$pid/cwd" 2>/dev/null || true)"
        if [ "$cwd" = "$NETBOX_PROJECT_DIR" ]; then
            printf '%s\n' "$pid"
        fi
    done < <(pgrep -u "$USER" -f 'manage.py runserver' || true)
}

runserver_is_running() {
    local pid

    while IFS= read -r pid; do
        if [ -n "$pid" ]; then
            return 0
        fi
    done < <(find_runserver_pids)

    return 1
}

stop_runserver() {
    local pid
    local stopped=1

    while IFS= read -r pid; do
        [ -n "$pid" ] || continue
        kill "$pid" >/dev/null 2>&1 || true
        stopped=0
    done < <(find_runserver_pids)

    return "$stopped"
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || {
        printf 'Missing required command: %s\n' "$1" >&2
        exit 1
    }
}

ensure_state_dir() {
    mkdir -p "$STATE_DIR"
    chmod 700 "$STATE_DIR"
}

load_credentials() {
    if [ -f "$CREDENTIALS_FILE" ]; then
        # The credentials file is generated by these scripts and uses shell-safe quoting.
        # Source it so escaped values round-trip correctly.
        set -a
        # shellcheck disable=SC1090
        . "$CREDENTIALS_FILE"
        set +a
    fi
}

docker_compose() {
    (
        cd "$DEVRUN_DIR"
        docker compose "$@"
    )
}

wait_for_postgres() {
    local attempt
    for attempt in $(seq 1 30); do
        if pg_isready -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
    done
    printf 'PostgreSQL did not become ready in time.\n' >&2
    return 1
}

wait_for_redis() {
    local attempt
    for attempt in $(seq 1 30); do
        if redis-cli -h 127.0.0.1 -p 6379 ping >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
    done
    printf 'Redis did not become ready in time.\n' >&2
    return 1
}

extract_plugin_blocker() {
    python3 - "$1" <<'PY'
import pathlib
import re
import sys

text = pathlib.Path(sys.argv[1]).read_text(errors='replace')
patterns = [
    r'^ModuleNotFoundError: .+$',
    r'^ImportError: .+$',
    r'^ImproperlyConfigured: .+$',
    r'^RuntimeError: .+$',
    r'^Exception: .+$',
    r'^.+Error: .+$',
    r'^Unable to load plugin .+$',
]
for line in text.splitlines():
    stripped = line.strip()
    if not stripped or stripped.startswith('Traceback ') or stripped.startswith('File "'):
        continue
    if stripped.startswith('raise ') or stripped.startswith('During handling'):
        continue
    for pattern in patterns:
        if re.match(pattern, stripped):
            print(stripped)
            raise SystemExit(0)
for line in text.splitlines():
    stripped = line.strip()
    if stripped:
        print(stripped)
        break
PY
}